FROM fusionauth/fusionauth-app:latest

EXPOSE 80
EXPOSE 443

# re-running command provided in image
# https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/fusionauth-app/Dockerfile
CMD ["/usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/catalina.sh", "run"]
