# Runs database migrations
FROM node:16

WORKDIR /usr/src/app

COPY ./prisma ./prisma/

RUN yarn add prisma

# Generate prisma client - ensure that there are no OS differences
CMD [ "npx", "prisma", "migrate", "deploy" ]
