import {
  InputAcceptTypeCsv,
  InputAcceptTypeExcel,
  InputAcceptTypeTsv,
  InputAcceptTypeXml,
  InputAcceptTypeZip,
  MimeType,
} from '@jetstream/types';

export const ORG_VERSION_PLACEHOLDER = '_DEFAULT_VERSION_';

export const SESSION_EXP_DAYS = 5;
export const SFDC_BULK_API_NULL_VALUE = '#N/A';
export const SFDC_BLANK_PICKLIST_VALUE = '--None--';

export const FEATURE_FLAGS = Object.freeze({
  ALL: 'all',
  AUTOMATION_CONTROL: 'automation-control',
  AUTOMATION_CONTROL_NEW: 'automation-control-new',
  QUERY: 'query',
  LOAD: 'load',
  LOAD_MULTI_OBJ: 'load-multi-object',
  PERMISSION_MANAGER: 'permission-manager',
  DEPLOYMENT: 'deployment',
  NOTIFICATIONS: 'notifications',
  ALLOW_GOOGLE_UPLOAD: 'allow-google-upload',
  UPDATE_RECORDS: 'update-records',
});

export const INPUT_ACCEPT_FILETYPES: {
  ZIP: InputAcceptTypeZip;
  CSV: InputAcceptTypeCsv;
  TSV: InputAcceptTypeTsv;
  EXCEL: InputAcceptTypeExcel;
  XML: InputAcceptTypeXml;
} = {
  ZIP: '.zip',
  CSV: '.csv',
  TSV: '.tsv',
  EXCEL: '.xlsx',
  XML: '.xml',
};

export const HTTP = {
  COOKIE: {
    JETSTREAM: 'jetstream',
  },
  HEADERS: {
    ACCEPT: 'Accept',
    X_CLIENT_REQUEST_ID: 'X-Client-Request-Id',
    X_REQUEST_ID: 'X-Request-Id',
    X_RETRY: 'X-RETRY',
    X_LOGOUT: 'X-AUTH-LOGOUT', // 1=true
    X_LOGOUT_URL: 'X-LOGOUT-URL',
    X_SFDC_ID: 'X-SFDC-ID',
    X_SFDC_API_VERSION: 'X-SFDC-API-VERSION',
    X_SFDC_ID_TARGET: 'X-SFDC-ID-TARGET',
    X_SFDC_API_TARGET_VERSION: 'X-SFDC-API-TARGET-VERSION',
    X_SFDC_ORG_CONNECTION_ERROR: 'X-SFDC-ORG-CONNECTION-ERROR',
    X_SFDC_Session: 'X-SFDC-SESSION',
    X_INCLUDE_CALL_OPTIONS: 'X_INCLUDE_CALL_OPTIONS',
    X_CACHE_RESPONSE: 'X-CACHE-RESPONSE',
    X_CACHE_KEY: 'X-CACHE-KEY',
    X_CACHE_AGE: 'X-CACHE-AGE',
    X_CACHE_EXP: 'X-CACHE-ECP',
    CONTENT_TYPE: 'Content-Type',
    X_MOCK_KEY: 'X-MOCK-KEY',
    X_FORWARDED_FOR: 'X-FORWARDED-FOR',
    CONTENT_DISPOSITION: 'Content-Disposition',
    CF_Connecting_IP: 'CF-Connecting-IP',
    CF_IPCountry: 'CF-IPCountry',
  },
  CONTENT_TYPE: {
    JSON: 'application/json',
    FORM_URL: 'application/x-www-form-urlencoded',
    XML: 'application/xml',
    XML_TEXT: 'text/xml',
    XML_UTF8: 'application/xml; charset=UTF-8',
    CSV: 'text/csv; charset=UTF-8',
    ZIP_CSV: 'zip/csv',
    ZIP: 'application/zip',
  },
};

export const ERROR_MESSAGES = {
  SFDC_EXPIRED_TOKEN: 'expired access/refresh token',
  SFDC_EXPIRED_TOKEN_VALIDITY: 'token validity expired',
  SFDC_ORG_DOES_NOT_EXIST: /^getaddrinfo ENOTFOUND [a-z0-9-.]+\.salesforce\.com$/i,
  SFDC_REST_API_NOT_ENABLED: /api is not enabled/i,
  SFDC_REST_API_NOT_ENABLED_MSG: 'Your org/user does not have API access which is required for Jetstream to communicate with Salesforce.',
} as const;

export const MIME_TYPES: {
  PLAN_TEXT: MimeType;
  CSV: MimeType;
  XLSX: MimeType;
  XLSX_OPEN_OFFICE: MimeType;
  JSON: MimeType;
  XML: MimeType;
  ZIP: MimeType;
  GSHEET: MimeType;
} = {
  PLAN_TEXT: 'text/plain;charset=utf-8',
  CSV: 'text/csv;charset=utf-8',
  XLSX: 'application/octet-stream;charset=utf-8',
  XLSX_OPEN_OFFICE: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  JSON: 'application/json;charset=utf-8',
  XML: 'text/xml;charset=utf-8',
  ZIP: 'application/zip;charset=utf-8',
  GSHEET: 'application/vnd.google-apps.spreadsheet',
};

export const fileExtToMimeType = {
  csv: MIME_TYPES.CSV,
  xlsx: MIME_TYPES.XLSX,
  json: MIME_TYPES.JSON,
  xml: MIME_TYPES.XML,
  zip: MIME_TYPES.ZIP,
};

export const fileExtToGoogleDriveMimeType = {
  csv: MIME_TYPES.GSHEET,
  xlsx: MIME_TYPES.GSHEET,
  json: MIME_TYPES.PLAN_TEXT,
  xml: MIME_TYPES.PLAN_TEXT,
  zip: MIME_TYPES.ZIP,
};

export const INDEXED_DB = {
  KEYS: {
    automationControlHistory: 'AUTOMATION:QUERY',
    queryHistory: 'HISTORY:QUERY',
    loadSavedMapping: 'LOAD:SAVED_MAPPING',
    apexHistory: 'HISTORY:APEX',
    deployHistory: 'HISTORY:DEPLOY',
    salesforceApiHistory: 'HISTORY:SALESFORCE_API',
    recordHistory: 'HISTORY:RECORDS',
    httpCache: 'HTTP:CACHE',
    userPreferences: 'USER:PREFERENCES',
    sobjectExportSelection: 'USER:SOBJECT_EXPORT_OPTIONS',
  },
};

export const YYYY_MM_DD = 'YYYY-MM-DD'; // NOT DATE-FN COMPATIBLE
export const YYYY_MM_DD__HH_mm_ss = 'YYYY-MM-DD HH:mm:ss'; // NOT DATE-FN COMPATIBLE
export const YYYY_MM_DD_HH_mm_ss_z = 'YYYY-MM-DDTHH:mm:ssZ'; // NOT DATE-FN COMPATIBLE

export const DATE_FORMATS = {
  MM_DD_YYYY: 'MM/DD/YYYY', // NOT DATE-FN COMPATIBLE
  DD_MM_YYYY: 'DD/MM/YYYY', // NOT DATE-FN COMPATIBLE
  yyyy_MM_dd: 'yyyy-MM-dd',
  YYYY_MM_DD, // NOT DATE-FN COMPATIBLE
  YYYY_MM_DD__HH_mm_ss, // NOT DATE-FN COMPATIBLE
  YYYY_MM_DD_HH_mm_ss_z, // NOT DATE-FN COMPATIBLE
  YYYY_MM_DD_HH_mm_ss_a: 'yyyy-MM-dd h:mm:ss a',
  HH_mm_ss_ssss_z: `HH:mm:ss'.'SSSS'Z'`,
  HH_MM_SS_A: 'h:mm:ss A', // NOT DATE-FN COMPATIBLE
  HH_MM_SS_a: 'h:mm:ss a',
  HH_MM_SS_SSSS: 'H:mm:ss.SSSS',
  FULL: 'MMMM do, yyyy hh:mm aa',
};

export const ANALYTICS_KEYS = {
  /** Browser Notifications */
  notifications_modal_opened: 'notifications_modal_opened',
  notifications_permission_requested: 'notifications_permission_requested',
  /** Record Modal */
  record_modal_action_change: 'record_modal_action_change',
  record_modal_view_related: 'record_modal_view_related',
  record_modal_view_children: 'record_modal_view_children',
  record_modal_download: 'record_modal_download',
  record_modal_json: 'record_modal_json',
  record_modal_save: 'record_modal_save',
  record_modal_clipboard: 'record_modal_clipboard',
  /** AUTOMATION CONTROL */
  automation_selection: 'automation_selection',
  automation_review: 'automation_review',
  automation_deploy: 'automation_deploy',
  automation_rollback: 'automation_rollback',
  automation_toggle_all: 'automation_toggle_all',
  automation_process_builder_refresh: 'automation_process_builder_refresh',
  automation_export: 'automation_export',
  /** QUERY */
  query_BulkDelete: 'query_BulkDelete',
  query_CopyToClipboard: 'query_CopyToClipboard',
  query_DownloadResults: 'query_DownloadResults',
  query_ExecuteQuery: 'query_ExecuteQuery',
  query_HelpClicked: 'query_HelpClicked',
  query_HistoryChangeOrgs: 'query_HistoryChangeOrgs',
  query_HistoryExecute: 'query_HistoryExecute',
  query_HistoryModalOpened: 'query_HistoryModalOpened',
  query_HistoryRestore: 'query_HistoryRestore',
  query_HistorySaveQueryToggled: 'query_HistorySaveQueryToggled',
  query_HistoryShowMore: 'query_HistoryShowMore',
  query_HistoryTypeChanged: 'query_HistoryTypeChanged',
  query_LoadMore: 'query_LoadMore',
  query_ManualQueryOpened: 'query_ManualQueryOpened',
  query_ManualSoqlOpened: 'query_ManualSoqlOpened',
  query_MetadataQueryToggled: 'query_MetadataQueryToggled',
  query_RecordAction: 'query_RecordAction',
  query_UpdateRecordsInline: 'query_UpdateRecordsInline',
  query_ResetPage: 'query_ResetPage',
  query_InlineEditSave: 'query_InlineEditSave',
  /** DOWNLOAD FILES */
  attachment_QueriedEligibleObject: 'attachment_QueriedEligibleObject',
  attachment_ModalOpened: 'attachment_ModalOpened',
  attachment_Cancelled: 'attachment_Cancelled',
  attachment_Downloaded: 'attachment_Downloaded',
  attachment_Error: 'attachment_Error',
  /** LOAD */
  load_GoBackToPrevStep: 'load_GoBackToPrevStep',
  load_MappingAutomationChanged: 'load_MappingAutomationChanged',
  load_SavedMappingLoaded: 'load_SavedMappingLoaded',
  load_MappingFilterChanged: 'load_MappingFilterChanged',
  load_MappingRowPreviewChanged: 'load_MappingRowPreviewChanged',
  load_StartOver: 'load_StartOver',
  load_Submitted: 'load_Submitted',
  load_ViewRecords: 'load_ViewRecords',
  load_DownloadRecords: 'load_DownloadRecords',
  /** MASS UPDATE */
  mass_update_Submitted: 'mass_update_Submitted',
  mass_update_ApplyAll: 'mass_update_ApplyAll',
  mass_update_DownloadRecords: 'mass_update_DownloadRecords',
  mass_update_ViewRecords: 'mass_update_ViewRecords',
  /** ANON APEX */
  apex_Submitted: 'apex_Submitted',
  /** SFDC API */
  sfdcApi_Submitted: 'sfdcApi_Submitted',
  sfdcApi_Sample: 'sfdcApi_Sample',
  /** DEPLOY */
  deploy_addToChangeset: 'deploy_addToChangeset',
  deploy_configuration: 'deploy_configuration',
  deploy_deployMetadata: 'deploy_deployMetadata',
  deploy_download: 'deploy_download',
  deploy_downloadMetadataPkg: 'deploy_downloadMetadataPkg',
  deploy_finished: 'deploy_finished',
  deploy_go_back: 'deploy_go_back',
  deploy_history_opened: 'deploy_history_opened',
  deploy_history_download_package: 'deploy_history_download_package',
  deploy_history_download_results: 'deploy_history_download_results',
  deploy_history_view_details: 'deploy_history_view_details',
  /** CREATE OBJECT */
  sobj_create_object: 'sobj_create_object',
  /** CREATE FIELDS */
  sobj_create_field_export_fields: 'sobj_create_field_export_fields',
  sobj_create_field_export_example: 'sobj_create_field_export_example',
  sobj_create_field_import_fields: 'sobj_create_field_import_fields',
  sobj_create_field_reset_rows: 'sobj_create_field_reset_rows',
  sobj_create_field_submit_modal_opened: 'sobj_create_field_submit_modal_opened',
  sobj_create_field_deploy: 'sobj_create_field_deploy',
  sobj_create_field_export_results: 'sobj_create_field_export_results',
  sobj_create_field_global_picklist: 'sobj_create_field_global_picklist',
  sobj_create_field_formula_execute: 'sobj_create_field_formula_execute',
  /** FORMULA EVALUATOR */
  formula_execute: 'formula_execute',
  formula_export_deploy: 'formula_export_deploy',
  formula_export_results: 'formula_export_results',
  /** Platform Event */
  platform_event_subscribed: 'platform_event_subscribed',
  platform_event_unsubscribe: 'platform_event_unsubscribe',
  platform_event_clear_all: 'platform_event_clear_all',
  platform_event_publish: 'platform_event_publish',
  /** Settings */
  settings_update_user: 'settings_update_user',
  settings_link_account: 'settings_link_account',
  settings_unlink_account: 'settings_unlink_account',
  settings_resend_email_verification: 'settings_resend_email_verification',
  settings_delete_account: 'settings_delete_account',

  /** FEEDBACK */
  donate_popover_open: 'donate_popover_open',
  donate_popover_cta_click: 'donate_popover_cta_click',
} as const;

export const LOG_LEVELS = ['NONE', 'ERROR', 'WARN', 'INFO', 'DEBUG', 'FINE', 'FINER', 'FINEST'];

export const TITLES = {
  BAR_JETSTREAM: '| Jetstream',
  QUERY: 'Query | Jetstream',
  LOAD: 'Load | Jetstream',
  AUTOMATION_CONTROL: 'Automation Control | Jetstream',
  MANAGE_PERMISSIONS: 'Manage Permissions | Jetstream',
  DEPLOY_METADATA: 'Deploy Metadata | Jetstream',
  CREATE_OBJ_FIELD: 'Create Fields | Jetstream',
  MASS_UPDATE_RECORDS: 'Update Records | Jetstream',
  ANON_APEX: 'Anonymous Apex | Jetstream',
  FORMULA_EVALUATOR: 'Formula Evaluator | Jetstream',
  DEBUG_LOGS: 'Debug Logs | Jetstream',
  API_EXPLORER: 'Salesforce Api | Jetstream',
  PLATFORM_EVENTS: 'Platform Events | Jetstream',
  FEEDBACK: 'Support & Feedback | Jetstream',
  SETTINGS: 'Account Settings | Jetstream',
};

export const SOCKET_EVENTS = {
  // PLATFORM EVENT
  PLATFORM_EVENT_MESSAGE: 'platform-event:message',
  PLATFORM_EVENT_SUBSCRIBE: 'platform-event:subscribe',
  PLATFORM_EVENT_UNSUBSCRIBE: 'platform-event:unsubscribe',
};

/**
 * Some built-in Salesforce Objects use a different field for the record Name
 * Most objects use "Name"
 */
export const SOBJECT_NAME_FIELD_MAP = {
  AccessControlPolicy: 'DeveloperName',
  AccountForecastSettings: 'DeveloperName',
  AcctMgrTargetSettings: 'DeveloperName',
  ActionLauncherItemDef: 'DeveloperName',
  ActionLinkGroupTemplate: 'DeveloperName',
  ActionPlanTmplPkgConfig: 'DeveloperName',
  ActivityHistory: 'Subject',
  ActivityRecurrence2: 'Subject',
  ActivityRecurrence2Exception: 'Subject',
  AdvAccountForecastSet: 'DeveloperName',
  AdvAcctForecastDimSource: 'DeveloperName',
  AdvAcctForecastPeriodGroup: 'DeveloperName',
  AIApplication: 'DeveloperName',
  AIApplicationConfig: 'DeveloperName',
  AIModel: 'DeveloperName',
  AllPackage: 'PackageName',
  AllPackageVersion: 'VersionName',
  AlternativePaymentMethod: 'AlternativePaymentMethodNumber',
  AnimationRule: 'DeveloperName',
  ApexTestSuite: 'TestSuiteName',
  ApiAnomalyEventStore: 'ApiAnomalyEventNumber',
  AssetAction: 'AssetActionNumber',
  AssetActionSource: 'AssetActionSourceNumber',
  AssetRelationship: 'AssetRelationshipNumber',
  AssetStatePeriod: 'AssetStatePeriodNumber',
  AssociatedLocation: 'AssociatedLocationNumber',
  AsyncOperationLog: 'AsyncOperationNumber',
  AttachedContentDocument: 'Title',
  AuraDefinitionBundle: 'DeveloperName',
  AuthConfig: 'DeveloperName',
  AuthProvider: 'FriendlyName',
  BatchCalcJobDefinition: 'DeveloperName',
  BatchJobDefinition: 'DeveloperName',
  BatchProcessJobDefinition: 'DeveloperName',
  BrandingSet: 'DeveloperName',
  BriefcaseDefinition: 'DeveloperName',
  CampaignInfluenceModel: 'MasterLabel',
  Canvas: 'DeveloperName',
  CardPaymentMethod: 'CardPaymentMethodNumber',
  Case: 'CaseNumber',
  CaseStatus: 'ApiName',
  Certificate: 'DeveloperName',
  ChangeRequest: 'ChangeRequestNumber',
  ChannelLayout: 'DeveloperName',
  ChatterExtension: 'DeveloperName',
  ChunkableTask: 'DeveloperName',
  ChunkableTask2: 'DeveloperName',
  CleanDataService: 'DeveloperName',
  CleanRule: 'DeveloperName',
  CompactLayout: 'DeveloperName',
  ComputedComponentMetadata: 'DeveloperName',
  ContentAsset: 'DeveloperName',
  ContentDocument: 'Title',
  ContentHubRepository: 'DeveloperName',
  ContentNote: 'Title',
  ContentVersion: 'Title',
  Contract: 'ContractNumber',
  ContractLineItem: 'LineItemNumber',
  ContractStatus: 'ApiName',
  CopyExport: 'DeveloperName',
  CorsWhitelistEntry: 'DeveloperName',
  CredentialStuffingEventStore: 'CredentialStuffingEventNumber',
  CreditMemo: 'DocumentNumber',
  CreditMemoInvApplication: 'CreditMemoInvoiceNumber',
  CspTrustedSite: 'DeveloperName',
  CustomApplication: 'DeveloperName',
  CustomConsoleComponent: 'DeveloperName',
  CustomField: 'DeveloperName',
  CustomHelpMenuSection: 'DeveloperName',
  CustomNotificationType: 'DeveloperName',
  CustomObject: 'DeveloperName',
  CustomPermission: 'DeveloperName',
  CustomTab: 'MasterLabel',
  Dashboard: 'Title',
  DataDotComEntitySetting: 'DeveloperName',
  DebugLevel: 'DeveloperName',
  DecisionMatrixDefinition: 'DeveloperName',
  DecisionMatrixDefinitionVersion: 'DeveloperName',
  DecisionTable: 'DeveloperName',
  DecisionTableDatasetLink: 'DeveloperName',
  DeliveryTaskStatus: 'ApiName',
  DigitalSignature: 'DigitalSignatureNumber',
  DigitalWallet: 'DigitalWalletNumber',
  DocumentType: 'MasterLabel',
  Domain: 'Domain',
  DuplicateJobDefinition: 'DeveloperName',
  DuplicateRule: 'DeveloperName',
  EmailServicesAddress: 'LocalPart',
  EmailServicesFunction: 'FunctionName',
  EmbeddedServiceBranding: 'DeveloperName',
  EmbeddedServiceConfig: 'DeveloperName',
  EmbeddedServiceMenuSettings: 'DeveloperName',
  EmployeeCrisisAssessment: 'AssessmentNumber',
  Event: 'Subject',
  EventChangeEvent: 'Subject',
  EventRelayConfig: 'DeveloperName',
  EventRelayFeedback: 'EventRelayNumber',
  ExperiencePropertyType: 'DeveloperName',
  ExpressionSetDefinition: 'DeveloperName',
  ExpressionSetDefinitionVersion: 'DeveloperName',
  ExpressionSetObjectAlias: 'DeveloperName',
  ExternalCredential: 'DeveloperName',
  ExternalDataSource: 'DeveloperName',
  ExternalDataSrcDescriptor: 'DeveloperName',
  ExternalServiceObjectType: 'DeveloperName',
  ExternalServiceOperation: 'DeveloperName',
  ExternalServiceRegistration: 'DeveloperName',
  FieldMapping: 'DeveloperName',
  FieldRestrictionRule: 'DeveloperName',
  FieldSecurityClassification: 'ApiName',
  FieldSet: 'MasterLabel',
  FinanceBalanceSnapshot: 'FinanceBalanceSnapshotNumber',
  FinanceTransaction: 'FinanceTransactionNumber',
  FlexiPage: 'DeveloperName',
  Flow: 'MasterLabel',
  FlowCategory: 'DeveloperName',
  FlowDefinition: 'DeveloperName',
  FlowTest: 'DeveloperName',
  FolderedContentDocument: 'Title',
  GlobalValueSet: 'DeveloperName',
  GtwyProvPaymentMethodType: 'MasterLabel',
  Idea: 'Title',
  InboundNetworkConnection: 'DeveloperName',
  Incident: 'IncidentNumber',
  Index: 'DeveloperName',
  InternalOrganizationUnit: 'OrganizationCode',
  Invoice: 'DocumentNumber',
  IPAddressRange: 'DeveloperName',
  JournalReason: 'ApiName',
  KnowledgeArticle: 'Title',
  KnowledgeArticleVersion: 'Title',
  LeadConvertSettings: 'DeveloperName',
  LeadStatus: 'ApiName',
  Lens: 'MasterLabel',
  LicenseDefinition: 'DeveloperName',
  LightningBolt: 'DeveloperName',
  LightningComponentBundle: 'DeveloperName',
  LightningExperienceTheme: 'DeveloperName',
  LightningMessageChannel: 'DeveloperName',
  LightningOnboardingConfig: 'DeveloperName',
  LinkedInLeadGenAdAccount: 'DeveloperName',
  LinkedInLeadGenConfig: 'DeveloperName',
  ListViewChart: 'DeveloperName',
  LocationGroup: 'LocationGroupName',
  LocationGroupAssignment: 'LocationGroupAssignment',
  LookedUpFromActivity: 'Subject',
  LookupFilter: 'DeveloperName',
  MailAppOwaWhitelist: 'DeveloperName',
  ManagedContentType: 'DeveloperName',
  MatchingRule: 'DeveloperName',
  MfgProgramTemplate: 'DeveloperName',
  MLDataDefinition: 'DeveloperName',
  MLPredictionDefinition: 'DeveloperName',
  MLRecommendationDefinition: 'DeveloperName',
  MobileApplicationDetail: 'DeveloperName',
  MutingPermissionSet: 'DeveloperName',
  MyDomainDiscoverableLogin: 'DeveloperName',
  NamedCredential: 'DeveloperName',
  Note: 'Title',
  OauthCustomScope: 'DeveloperName',
  ObjectHierarchyRelationship: 'DeveloperName',
  ObjectMapping: 'DeveloperName',
  OmniDataTransformConfig: 'DeveloperName',
  OmniIntegrationProcConfig: 'DeveloperName',
  OmniInteractionAccessConfig: 'DeveloperName',
  OmniInteractionConfig: 'DeveloperName',
  OmniScriptConfig: 'DeveloperName',
  OmniUiCardConfig: 'DeveloperName',
  OpenActivity: 'Subject',
  OpportunitySplit: 'Split',
  OpportunitySplitType: 'DeveloperName',
  OpportunityStage: 'ApiName',
  Order: 'OrderNumber',
  OrderItem: 'OrderItemNumber',
  OrderItemType: 'ApiName',
  OrderStatus: 'ApiName',
  OutboundNetworkConnection: 'DeveloperName',
  OwnedContentDocument: 'Title',
  PackageBooleanValue: 'DeveloperName',
  PackageDateValue: 'DeveloperName',
  PackageIntegerValue: 'DeveloperName',
  PackageOperationError: 'SequenceNumber',
  PartitionLevelScheme: 'DeveloperName',
  PartnerRole: 'ApiName',
  PathAssistant: 'DeveloperName',
  PathAssistantStepInfo: 'DeveloperName',
  Payment: 'PaymentNumber',
  PaymentAuthAdjustment: 'PaymentAuthAdjustmentNumber',
  PaymentAuthorization: 'PaymentAuthorizationNumber',
  PaymentGateway: 'PaymentGatewayName',
  PaymentGatewayLog: 'PaymentGatewayLogNumber',
  PaymentGatewayProvider: 'MasterLabel',
  PaymentGroup: 'PaymentGroupNumber',
  PaymentLineInvoice: 'PaymentLineInvoiceNumber',
  PermissionSetGroup: 'DeveloperName',
  PermissionSetLicense: 'DeveloperName',
  PermissionSetLicenseDefinition: 'DeveloperName',
  PlatformCachePartition: 'DeveloperName',
  PlatformEventChannel: 'DeveloperName',
  PlatformEventChannelMember: 'DeveloperName',
  PlatformEventSubscriberConfig: 'DeveloperName',
  Problem: 'ProblemNumber',
  ProcessFlowMigration: 'DeveloperName',
  ProductItem: 'ProductItemNumber',
  ProductItemTransaction: 'ProductItemTransactionNumber',
  ProductRequired: 'ProductRequiredNumber',
  ProductTransfer: 'ProductTransferNumber',
  Prompt: 'DeveloperName',
  QuickActionDefinition: 'DeveloperName',
  RecommendationStrategy: 'DeveloperName',
  RecordActionDeployment: 'DeveloperName',
  RedirectWhitelistUrl: 'DeveloperName',
  Refund: 'RefundNumber',
  RefundLinePayment: 'RefundLinePaymentNumber',
  RemoteProxy: 'SiteName',
  ReportAnomalyEventStore: 'ReportAnomalyEventNumber',
  RestrictionRule: 'DeveloperName',
  SalesAgreementSettings: 'DeveloperName',
  SamlSsoConfig: 'DeveloperName',
  SandOmInfo: 'DeveloperName',
  Scontrol: 'DeveloperName',
  SearchCustomization: 'DeveloperName',
  SecurityCustomBaseline: 'DeveloperName',
  SessionHijackingEventStore: 'SessionHijackingEventNumber',
  SessionLevelPolicy: 'DeveloperName',
  SetupApp: 'DeveloperName',
  Shipment: 'ShipmentNumber',
  ShipmentItem: 'ShipmentItemNumber',
  SlackApp: 'DeveloperName',
  Solution: 'SolutionName',
  SolutionStatus: 'ApiName',
  SOSDeployment: 'DeveloperName',
  Task: 'Subject',
  TaskChangeEvent: 'Subject',
  TaskPriority: 'ApiName',
  TaskStatus: 'ApiName',
  ThreatDetectionFeedback: 'ThreatDetectionFeedbackNumber',
  TransactionSecurityPolicy: 'DeveloperName',
  UiFormulaRule: 'DeveloperName',
  UserAppMenuItem: 'Label',
  UserProfileSearchScope: 'DeveloperName',
  UserProvisioningConfig: 'DeveloperName',
  ValidationRule: 'ValidationName',
  ViewDefinition: 'DeveloperName',
  WorkflowAlert: 'Description',
  WorkflowTask: 'Subject',
  WorkOrder: 'WorkOrderNumber',
  WorkOrderLineItem: 'LineItemNumber',
  WorkOrderLineItemStatus: 'ApiName',
  WorkOrderStatus: 'ApiName',
  WorkPlanTemplateEntry: 'WorkPlanTemplateEntryNumber',
  WorkStepStatus: 'ApiName',
} as const;

export const RECORD_PREFIX_MAP = {
  '110': 'ObjectPermissions',
  '130': 'Address',
  '131': 'Location',
  '500': 'Case',
  '501': 'Solution',
  '550': 'Entitlement',
  '551': 'EntitlementTemplate',
  '557': 'MilestoneType',
  '574': 'QuickText',
  '701': 'Campaign',
  '709': 'ApexTestQueueItem',
  '800': 'Contract',
  '801': 'Order',
  '802': 'OrderItem',
  '810': 'ServiceContract',
  '811': 'ContractLineItem',
  '001': 'Account',
  '02Z': 'AccountContactRole',
  '00I': 'Partner',
  '01M': 'AccountTeamMember',
  '07g': 'ActionLinkGroupTemplate',
  '07l': 'ActionLinkTemplate',
  '07r': 'ActionPlan',
  '07s': 'ActionPlanItem',
  '0my': 'ActionPlanItemDependency',
  '0PR': 'ActionPlanTemplate',
  '0PJ': 'ActionPlanTemplateItem',
  '0PN': 'ActionPlanTemplateItemValue',
  '0PT': 'ActionPlanTemplateVersion',
  '0yy': 'ActionPlanTmplPkgConfig',
  '0mx': 'ActionPlnTmplItmDependency',
  '04m': 'AdditionalNumber',
  '8Z7': 'AlternativePaymentMethod',
  '0Bt': 'Announcement',
  '01p': 'ApexClass',
  '099': 'ApexComponent',
  '06j': 'ApexEmailNotification',
  '066': 'ApexPage',
  '07M': 'ApexTestResult',
  '05n': 'ApexTestResultLimits',
  '05m': 'ApexTestRunResult',
  '05F': 'ApexTestSuite',
  '01q': 'ApexTrigger',
  '0XI': 'AppAnalyticsQueryRequest',
  '0j8': 'AppUsageAssignment',
  '0eu': 'AssessmentIndicatorDefinition',
  '0eg': 'AssessmentTask',
  '0dQ': 'AssessmentTaskContentDocument',
  '0Z4': 'AssessmentTaskDefinition',
  '0dt': 'AssessmentTaskIndDefinition',
  '0es': 'AssessmentTaskOrder',
  '02i': 'Asset',
  '1AR': 'AssetRelationship',
  '0Kt': 'AssociatedLocation',
  '00P': 'Attachment',
  '0Ad': 'AuraDefinition',
  '0Ab': 'AuraDefinitionBundle',
  '0SO': 'AuthProvider',
  '0cI': 'AuthorizationForm',
  '0cK': 'AuthorizationFormConsent',
  '0cM': 'AuthorizationFormDataUse',
  '0cN': 'AuthorizationFormText',
  '9N1': 'BatchCalcJobDefinition',
  '0mh': 'BatchProcessJobDefinition',
  '016': 'BrandTemplate',
  '0Lw': 'BrandingSet',
  '0Ly': 'BrandingSetProperty',
  '5LH': 'BriefcaseAssignment',
  '1BU': 'BusinessBrand',
  '01m': 'BusinessHours',
  '019': 'BusinessProcess',
  '06Z': 'CalcProcStepRelationship',
  '0lI': 'CalculationMatrix',
  '0lJ': 'CalculationMatrixColumn',
  '9mt': 'CalculationMatrixRow',
  '0lN': 'CalculationMatrixVersion',
  '0k0': 'CalculationProcedure',
  '0mq': 'CalculationProcedureStep',
  '0kJ': 'CalculationProcedureVariable',
  '0k1': 'CalculationProcedureVersion',
  '03A': 'CalendarView',
  '04v': 'CallCenter',
  '0hn': 'CallCoachingMediaProvider',
  '00v': 'CampaignMember',
  '01Y': 'CampaignMemberStatus',
  '03O': 'CardPaymentMethod',
  '03j': 'CaseContactRole',
  '0oL': 'CaseRelatedIssue',
  '010': 'CaseSolution',
  '02o': 'CategoryData',
  '02n': 'CategoryNode',
  '0oW': 'ChangeRequest',
  '0oK': 'ChangeRequestRelatedIssue',
  '0tC': 'ChangeRequestRelatedItem',
  '0MY': 'ChatterExtension',
  '0Ob': 'ChatterExtensionConfig',
  '0F9': 'CollaborationGroup',
  '0FB': 'CollaborationGroupMember',
  '0I5': 'CollaborationGroupMemberRequest',
  '0H1': 'CollaborationInvitation',
  '0Xl': 'CommSubscription',
  '0eB': 'CommSubscriptionChannelType',
  '0dY': 'CommSubscriptionConsent',
  '0al': 'CommSubscriptionTiming',
  '0Ah': 'ConferenceNumber',
  '0Mo': 'ConsumptionRate',
  '0Mh': 'ConsumptionSchedule',
  '003': 'Contact',
  '8lW': 'ContactPointAddress',
  '0ZX': 'ContactPointConsent',
  '9Vl': 'ContactPointEmail',
  '0Ow': 'ContactPointPhone',
  '0ZY': 'ContactPointTypeConsent',
  '0Tz': 'ContactRequest',
  '03S': 'ContentAsset',
  '05D': 'ContentDistribution',
  '06A': 'ContentDocumentLink',
  '07H': 'ContentFolder',
  '068': 'ContentVersion',
  '058': 'ContentWorkspace',
  '059': 'ContentWorkspaceDoc',
  '05A': 'ContentWorkspaceMember',
  '05P': 'ContentWorkspacePermission',
  '02a': 'ContractContactRole',
  '074': 'CorsWhitelistEntry',
  '08y': 'CspTrustedSite',
  '01L': 'CurrencyType',
  '07W': 'CustomBrand',
  '07X': 'CustomBrandAsset',
  '2Ca': 'CustomHelpMenuItem',
  '2Cx': 'CustomHelpMenuSection',
  '0ML': 'CustomNotificationType',
  '0o6': 'Customer',
  '06E': 'DandBCompany',
  '0ZT': 'DataUseLegalBasis',
  '0ZW': 'DataUsePurpose',
  '04w': 'DatedConversionRate',
  '9QN': 'DecisionMatrixDefinition',
  '9QO': 'DecisionMatrixDefinitionVersion',
  '0lD': 'DecisionTable',
  '0lX': 'DecisionTableDatasetLink',
  '0lP': 'DecisionTableParameter',
  '0lZ': 'DecisionTblDatasetParameter',
  '1DS': 'DigitalSignature',
  '1DW': 'DigitalWallet',
  '015': 'Document',
  '05X': 'DocumentAttachmentMap',
  '0GL': 'DuplicateRecordItem',
  '0GK': 'DuplicateRecordSet',
  '06F': 'EmailCapture',
  '0T6': 'EmailDomainFilter',
  '09P': 'EmailDomainKey',
  '02s': 'EmailMessage',
  '0CZ': 'EmailMessageRelation',
  '26Z': 'EmailRelay',
  '093': 'EmailServicesAddress',
  '091': 'EmailServicesFunction',
  '00X': 'EmailTemplate',
  '0eF': 'EngagementChannelType',
  '0Rn': 'EnhancedLetterhead',
  '0E7': 'EntitlementContact',
  '0E8': 'EntitySubscription',
  '00U': 'Event',
  '0RE': 'EventRelation',
  '1GS': 'ExpressionFilter',
  '8BM': 'ExpressionFilterCriteria',
  '9QL': 'ExpressionSet',
  '9QA': 'ExpressionSetDefinition',
  '9QB': 'ExpressionSetDefinitionVersion',
  '0xV': 'ExpressionSetObjectAlias',
  '9QM': 'ExpressionSetVersion',
  '0XU': 'ExternalDataUserAuth',
  '0AY': 'ExternalEvent',
  '08N': 'ExternalEventMapping',
  '08M': 'FeedAttachment',
  '0D7': 'FeedComment',
  '0D5': 'FeedItem',
  '01k': 'FieldPermissions',
  '0n3': 'FinanceTransaction',
  '31z': 'FlowRecordRelation',
  '00l': 'Folder',
  '00G': 'Group',
  '011': 'GroupMember',
  '1gp': 'GtwyProvPaymentMethodType',
  '0C0': 'Holiday',
  '9s4': 'IPAddressRange',
  '087': 'Idea',
  '6TS': 'IframeWhiteListUrl',
  '4YL': 'Image',
  '0ny': 'Incident',
  '0tA': 'IncidentRelatedItem',
  '0PK': 'Individual',
  '00Q': 'Lead',
  '0fw': 'LegalEntity',
  '0S1': 'LightningExperienceTheme',
  '7MM': 'LightningOnboardingConfig',
  '0XB': 'ListEmail',
  '0XF': 'ListEmailIndividualRecipient',
  '0XD': 'ListEmailRecipientSource',
  '0Dd': 'ListViewChart',
  '0gh': 'LocationGroup',
  '0gx': 'LocationGroupAssignment',
  '0JZ': 'Macro',
  '0Ji': 'MacroInstruction',
  '01H': 'MailmergeTemplate',
  '7C1': 'MlQueryObservation',
  '0IW': 'MobileApplicationDetail',
  '0QM': 'MutingPermissionSet',
  '4hy': 'MyDomainDiscoverableLogin',
  '002': 'Note',
  '7ud': 'OauthCustomScope',
  '7ue': 'OauthCustomScopeApp',
  '0nc': 'OmniDataPack',
  '0jI': 'OmniDataTransform',
  '3UL': 'OmniDataTransformConfig',
  '0kd': 'OmniDataTransformItem',
  '0nL': 'OmniESignatureTemplate',
  '0qr': 'OmniIntegrationProcConfig',
  '0nz': 'OmniInteractionAccessConfig',
  '0yY': 'OmniInteractionConfig',
  '0jN': 'OmniProcess',
  '0k7': 'OmniProcessCompilation',
  '0kE': 'OmniProcessElement',
  '0nM': 'OmniProcessTransientData',
  '0qh': 'OmniScriptConfig',
  '0kT': 'OmniScriptSavedSession',
  '0ko': 'OmniUiCard',
  '9AK': 'OmniUiCardConfig',
  '0UG': 'OnboardingMetrics',
  '006': 'Opportunity',
  '00J': 'OpportunityCompetitor',
  '00K': 'OpportunityContactRole',
  '00k': 'OpportunityLineItem',
  '10X': 'OpportunityLineItemSplit',
  '049': 'OpportunitySplit',
  '00q': 'OpportunityTeamMember',
  '0dr': 'OrgDeleteRequest',
  '3v1': 'OrgMetric',
  '9aM': 'OrgMetricScanResult',
  '6mX': 'OrgMetricScanSummary',
  '0D2': 'OrgWideEmailAddress',
  '8kJ': 'OtherComponentTask',
  '0Q1': 'OutgoingEmail',
  '0Q3': 'OutgoingEmailRelation',
  '0g8': 'PartyConsent',
  '0aQ': 'Payment',
  '9tv': 'PaymentAuthAdjustment',
  '0Xc': 'PaymentAuthorization',
  '0b0': 'PaymentGateway',
  '0Xt': 'PaymentGatewayLog',
  '0cJ': 'PaymentGatewayProvider',
  '9zx': 'PaymentGroup',
  '1PL': 'PaymentLineInvoice',
  '0PS': 'PermissionSet',
  '0Pa': 'PermissionSetAssignment',
  '0PG': 'PermissionSetGroup',
  '0PM': 'PermissionSetGroupComponent',
  '2LA': 'PermissionSetLicenseAssign',
  '01P': 'PermissionSetTabSetting',
  '0Er': 'PlatformCachePartition',
  '0Ev': 'PlatformCachePartitionType',
  '01s': 'Pricebook2',
  '01u': 'PricebookEntry',
  '0o2': 'Problem',
  '0oE': 'ProblemIncident',
  '0tB': 'ProblemRelatedItem',
  '01t': 'Product2',
  '0Mq': 'ProductConsumptionSchedule',
  '0E9': 'ProductEntitlementTemplate',
  '0fK': 'ProductFulfillmentLocation',
  '0Co': 'ProductItem',
  '0TR': 'ProductItemTransaction',
  '0Gn': 'ProductRequired',
  '0Lu': 'ProductTransfer',
  '00e': 'Profile',
  '0bs': 'Prompt',
  '0bu': 'PromptAction',
  '4Dr': 'PromptError',
  '0bt': 'PromptVersion',
  '0IF': 'PushTopic',
  '0PX': 'PushUpgradeExcludedOrg',
  '03g': 'QueueSobject',
  '0io': 'ReceivedDocument',
  '0s0': 'ReceivedDocumentType',
  '0pr': 'Recommendation',
  '0rr': 'RecommendationResponse',
  '0Rw': 'RecordAction',
  '012': 'RecordType',
  '0v9': 'RecurrenceSchedule',
  '9V6': 'RedirectWhitelistUrl',
  '0cb': 'Refund',
  '0dR': 'RefundLinePayment',
  '0NW': 'SOSDeployment',
  '0NX': 'SOSSession',
  '0NZ': 'SOSSessionActivity',
  '0J4': 'SPSamlAttributes',
  '01f': 'Scorecard',
  '0Qn': 'ScorecardAssociation',
  '0Om': 'ScorecardMetric',
  '0MD': 'SearchPromotionRule',
  '09v': 'SecurityCustomBaseline',
  '0q6': 'Seller',
  '3Ys': 'SetupAssistantStep',
  '0J0': 'SetupEntityAccess',
  '0OB': 'Shipment',
  '0ob': 'ShipmentItem',
  '7Oh': 'SignatureTask',
  '6st': 'SignatureTaskLineItem',
  '0Xs': 'SiteIframeWhiteListUrl',
  '0H0': 'SiteRedirectMapping',
  '081': 'StaticResource',
  '0M6': 'StreamingChannel',
  '00T': 'Task',
  '0Hd': 'TestSuiteMembership',
  '0hY': 'ThreatDetectionFeedback',
  '0Jz': 'TodayGoal',
  '0TO': 'Topic',
  '0FT': 'TopicAssignment',
  '0NI': 'TransactionSecurityPolicy',
  '005': 'User',
  '01D': 'UserAccountTeamMember',
  '0Ds': 'UserAppInfo',
  '0Nw': 'UserAppMenuCustomization',
  '0UV': 'UserEmailPreferredPerson',
  '0Na': 'UserListView',
  '0JU': 'UserListViewCriterion',
  '051': 'UserPackageLicense',
  '03u': 'UserPreference',
  '0Ni': 'UserProvAccount',
  '0HY': 'UserProvAccountStaging',
  '0HX': 'UserProvMockTarget',
  '0Je': 'UserProvisioningConfig',
  '0Hs': 'UserProvisioningLog',
  '0HP': 'UserProvisioningRequest',
  '00E': 'UserRole',
  '00p': 'UserTeamMember',
  '0Z5': 'Visit',
  '0eV': 'VisitedParty',
  '0eW': 'Visitor',
  '083': 'Vote',
  '0UZ': 'WaveAutoInstallRequest',
  '00b': 'WebLink',
  '0WO': 'WorkOrder',
  '1WL': 'WorkOrderLineItem',
  '0gq': 'WorkPlan',
  '7Iy': 'WorkPlanTemplate',
  '8xu': 'WorkPlanTemplateEntry',
  '0hF': 'WorkStep',
  '4L0': 'WorkStepTemplate',
} as const;

/**
 * All Names and FullNames are provided as keys and values
 * This is to allow for easy lookup of either
 * FullNames with special characters are listed both with encoded and decoded values
 */
export const PROFILE_NAME_TO_FULL_NAME_MAP = {
  'Analytics Cloud Integration User': 'Analytics Cloud Integration User',
  'Analytics Cloud Security User': 'Analytics Cloud Security User',
  'Authenticated Website': 'PlatformPortal',
  PlatformPortal: 'Authenticated Website',
  'B2B Reordering Portal Buyer Profile': 'B2B Reordering Portal Buyer Profile',
  'Chatter External User': 'Chatter External User',
  'Chatter Free User': 'Chatter Free User',
  'Chatter Moderator User': 'Chatter Moderator User',
  'Contract Manager': 'ContractManager',
  ContractManager: 'Contract Manager',
  'Cross Org Data Proxy User': 'Cross Org Data Proxy User',
  'Custom: Marketing Profile': 'Custom: Marketing Profile',
  'Custom%3A Marketing Profile': 'Custom: Marketing Profile',
  'Custom: Sales Profile': 'Custom: Sales Profile',
  'Custom%3A Sales Profile': 'Custom: Sales Profile',
  'Custom: Support Profile': 'Custom: Support Profile',
  'Custom%3A Support Profile': 'Custom: Support Profile',
  'Customer Community Login User': 'Customer Community Login User',
  'Customer Community Plus Login User': 'Customer Community Plus Login User',
  'Customer Community Plus User': 'Customer Community Plus User',
  'Customer Community User': 'Customer Community User',
  'Customer Portal Manager Custom': 'Customer Portal Manager Custom',
  'Customer Portal Manager Standard': 'Customer Portal Manager Standard',
  'External Apps Login User': 'External Apps Login User',
  'External Identity User': 'External Identity User',
  'Force.com - App Subscription User': 'Force.com - App Subscription User',
  'Force%2Ecom - App Subscription User': 'Force.com - App Subscription User',
  'Force.com - Free User': 'Force.com - Free User',
  'Force%2Ecom - Free User': 'Force.com - Free User',
  'Gold Partner User': 'Gold Partner User',
  'Guest License User': 'Guest License User',
  'High Volume Customer Portal': 'HighVolumePortal',
  HighVolumePortal: 'High Volume Customer Portal',
  'High Volume Customer Portal User': 'High Volume Customer Portal User',
  'Identity User': 'Identity User',
  'Marketing User': 'MarketingProfile',
  MarketingProfile: 'Marketing User',
  'Minimum Access - Salesforce': 'Minimum Access - Salesforce',
  'My Community Profile': 'My Community Profile',
  'My Help Community Profile': 'My Help Community Profile',
  'Partner App Subscription User': 'Partner App Subscription User',
  'Partner Community Login User': 'Partner Community Login User',
  'Partner Community User': 'Partner Community User',
  'Read Only': 'Read Only',
  'Salesforce API Only System Integrations': 'Salesforce API Only System Integrations',
  'Silver Partner User': 'Silver Partner User',
  'Solution Manager': 'SolutionManager',
  SolutionManager: 'Solution Manager',
  'Standard Guest': 'Guest',
  Guest: 'Standard Guest',
  'Standard Platform User': 'StandardAul',
  StandardAul: 'Standard Platform User',
  'Standard User': 'Standard',
  Standard: 'Standard User',
  'System Administrator': 'Admin',
  Admin: 'System Administrator',
};
