import * as dotenv from 'dotenv';
dotenv.config();

export const ENV = {
  // SYSTEM
  NODE_ENV: process.env.NODE_ENV,
  ENVIRONMENT: process.env.ENVIRONMENT || 'production',
  PORT: process.env.port || 3333,
  // JETSTREAM
  JETSTREAM_SERVER_DOMAIN: process.env.JETSTREAM_SERVER_DOMAIN,
  JESTREAM_SESSION_SECRET: process.env.JESTREAM_SESSION_SECRET,
  JETSTREAM_SERVER_URL: process.env.JETSTREAM_SERVER_URL,
  JESTREAM_POSTGRES_DBURI: process.env.JESTREAM_POSTGRES_DBURI,
  JETSTREAM_CLIENT_URL: process.env.JETSTREAM_CLIENT_URL,
  // AUTH
  AUTH0_DOMAIN: process.env.AUTH0_DOMAIN,
  AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID,
  AUTH0_CLIENT_SECRET: process.env.AUTH0_CLIENT_SECRET,
  // MAILCHIMP
  MAILCHIMP_USER: process.env.MAILCHIMP_USER,
  MAILCHIMP_API_KEY: process.env.MAILCHIMP_API_KEY,
  MAILCHIMP_AUDIENCE_ID: process.env.MAILCHIMP_AUDIENCE_ID,
  // SFDC
  SFDC_FALLBACK_API_VERSION: process.env.SFDC_FALLBACK_API_VERSION,
  SFDC_CONSUMER_SECRET: process.env.SFDC_CONSUMER_SECRET,
  SFDC_CONSUMER_KEY: process.env.SFDC_CONSUMER_KEY,
  SFDC_CALLBACK_URL: process.env.SFDC_CALLBACK_URL,
};
