export const METADATA_TYPES_TO_OMIT = new Set([
  'AssignmentRules', // use AssignmentRule instead
  'AutoResponseRule', // use AutoResponseRules instead
  'EscalationRules', // use EscalationRule instead
  'ManagedTopic', // use ManagedTopics instead
  'MatchingRules', // use MatchingRule instead
  'CustomLabels', // use CustomLabel instead
  'Workflow', // use individual parts instead
  // 'Report', // these take FOREVER in real orgs, so maybe we should ignore them - tons of folders
]);

export const COMMON_METADATA_TYPES = [
  'ApexClass',
  'ApexComponent',
  'ApexPage',
  'ApexTrigger',
  'AuraDefinitionBundle',
  'CustomField',
  'CustomLabel',
  'CustomMetadata',
  'CustomObject',
  'CustomTab',
  'DuplicateRule',
  'EmailTemplate',
  'FieldSet',
  'FlexiPage',
  'Flow',
  'FlowDefinition',
  'GlobalValueSet',
  'LightningComponentBundle',
  'ListView',
  'MutingPermissionSet',
  'PermissionSet',
  'PermissionSetGroup',
  'Profile',
  'RecordType',
  'RemoteSiteSetting',
  'ReportType',
  'Role',
  'StandardValueSet',
  'StaticResource',
  'ValidationRule',
  'WebLink',
  'WorkflowAlert',
  'WorkflowFieldUpdate',
  'WorkflowKnowledgePublish',
  'WorkflowOutboundMessage',
  'WorkflowRule',
  'WorkflowSend',
  'WorkflowTask',
];

export const METADATA_LABEL_MAP = {
  AccountRelationshipShareRule: 'Account Relationship Share Rules',
  AccessControlPolicy: 'Access Control Policies',
  ActionLinkGroupTemplate: 'Action Link Group Templates',
  AIAssistantTemplate: 'AI Assistant Templates',
  AnalyticSnapshot: 'Analytic Snapshots',
  AnimationRule: 'Animation Rules',
  ApexClass: 'Apex Classes',
  ApexComponent: 'Visualforce Components',
  ApexEmailNotifications: 'Apex Email Notifications',
  ApexPage: 'Visualforce Pages',
  ApexTestSuite: 'Apex Test Suites',
  ApexTrigger: 'Apex Triggers',
  AppMenu: 'App Menus',
  ApprovalProcess: 'Approval Processes',
  AssignmentRule: 'Assignment Rules',
  AssignmentRules: 'Assignment Rules',
  AssistantRecommendationType: 'Assistant Recommendation Types',
  AuraDefinitionBundle: 'Aura Components',
  AuthProvider: 'Auth Providers',
  AutoResponseRules: 'Auto Response Rules',
  BlacklistedConsumer: 'Blacklisted Consumer',
  BrandingSet: 'Branding Sets',
  BusinessProcess: 'Business Processes',
  CallCenter: 'Call Centers',
  CallCoachingMediaProvider: 'Call Coaching Media Providers',
  CampaignInfluenceModel: 'Campaign Influence Models',
  CanvasMetadata: 'Canvas Metadata',
  CaseSubjectParticle: 'Case Subject Particles',
  Certificate: 'Certificates',
  ChannelLayout: 'Channel Layouts',
  ChatterExtension: 'Chatter Extensions',
  CleanDataService: 'Clean Data Services',
  CommandAction: 'Command Actions',
  Community: 'Communities',
  CommunityTemplateDefinition: 'Community Template Definitions',
  CommunityThemeDefinition: 'Community Theme Definitions',
  CompactLayout: 'Compact Layouts',
  ConnectedApp: 'Connected Apps',
  ContentAsset: 'Content Assets',
  CorsWhitelistOrigin: 'Cors Whitelist Origins',
  CspTrustedSite: 'Csp Trusted Sites',
  CustomApplication: 'Custom Applications',
  CustomApplicationComponent: 'Custom Application Components',
  CustomDataType: 'Custom Data Types',
  CustomExperience: 'Custom Experiences',
  CustomFeedFilter: 'Custom Feed Filters',
  CustomField: 'Custom Fields',
  CustomFieldTranslation: 'Custom Field Translations',
  CustomHelpMenuSection: 'Custom Help Menu Sections',
  CustomLabel: 'Custom Labels',
  CustomMetadata: 'Custom Metadata',
  CustomNotificationType: 'Custom Notification Types',
  CustomObject: 'Custom Objects',
  CustomObjectTranslation: 'Custom Object Translations',
  CustomPageWebLink: 'Custom Page Web Links',
  CustomPermission: 'Custom Permissions',
  CustomSite: 'Custom Sites',
  CustomTab: 'Custom Tabs',
  Dashboard: 'Dashboards',
  DashboardFolder: 'Dashboard Folders',
  DataCategoryGroup: 'Data Category Groups',
  DataPipeline: 'Data Pipelines',
  DelegateGroup: 'Delegate Groups',
  Document: 'Documents',
  DocumentFolder: 'Document Folders',
  DuplicateRule: 'Duplicate Rules',
  EclairGeoData: 'Eclair Geo Data',
  EmailFolder: 'Email Template Folders',
  EmailServicesFunction: 'Email Services Functions',
  EmailTemplate: 'Email Templates',
  EmbeddedServiceBranding: 'Embedded Service Branding',
  EmbeddedServiceConfig: 'Embedded Service Configs',
  EmbeddedServiceFieldService: 'Embedded Service Field Services',
  EmbeddedServiceFlowConfig: 'Embedded Service Flow Configs',
  EmbeddedServiceLiveAgent: 'Embedded Service Live Agents',
  EmbeddedServiceMenuSettings: 'Embedded Service Menu Settings',
  EntitlementProcess: 'Entitlement Processes',
  EntitlementTemplate: 'Entitlement Templates',
  EscalationRule: 'Escalation Rules',
  EscalationRules: 'Escalation Rules',
  EventDelivery: 'Event Deliveries',
  EventSubscription: 'Event Subscriptions',
  EventType: 'Event Types',
  ExperienceBundle: 'Experience Bundles',
  ExternalDataSource: 'External Data Sources',
  ExternalServiceRegistration: 'External Service Registrations',
  FeatureParameterBoolean: 'Feature Parameter Booleans',
  FeatureParameterDate: 'Feature Parameter Dates',
  FeatureParameterInteger: 'Feature Parameter Integers',
  FieldSet: 'Field Sets',
  FlexiPage: 'Lightning Record Pages',
  Flow: 'Flows',
  FlowCategory: 'Flow Categories',
  FlowDefinition: 'Flow Definitions',
  Form: 'Forms',
  GlobalPicklist: 'Global Picklists',
  GlobalValueSet: 'Global Value Sets (Pick lists)',
  GlobalValueSetTranslation: 'Global Value Set Translations',
  Group: 'Groups',
  HomePageComponent: 'Home Page Components',
  HomePageLayout: 'Home Page Layouts',
  InboundNetworkConnection: 'Inbound Network Connections',
  Index: 'Indexes',
  InsightType: 'Insight Types',
  InstalledPackage: 'Installed Packages',
  IntegrationHubSettings: 'Integration Hub Settings',
  IntegrationHubSettingsType: 'Integration Hub Settings Types',
  KeywordList: 'Keyword Lists',
  Layout: 'Page Layouts',
  LeadConvertSettings: 'Lead Convert Settings',
  Letterhead: 'Letterheads',
  LicenseDefinition: 'License Definitions',
  LightningBolt: 'Lightning Bolts',
  LightningComponentBundle: 'Lightning Web Components (LWC)',
  LightningExperienceTheme: 'Lightning Experience Themes',
  LightningMessageChannel: 'Lightning Message Channels',
  LightningOnboardingConfig: 'Lightning Onboarding Configs',
  ListView: 'List Views',
  LiveChatAgentConfig: 'Live Chat Agent Configs',
  LiveChatButton: 'Live Chat Buttons',
  LiveChatDeployment: 'Live Chat Deployments',
  LiveChatSensitiveDataRule: 'Live Chat Sensitive Data Rules',
  ManagedContentType: 'Managed Content Types',
  ManagedTopics: 'Managed Topics',
  MarketingResourceType: 'Marketing Resource Types',
  MatchingRule: 'Matching Rules',
  MatchingRules: 'Matching Rules',
  MilestoneType: 'Milestone Types',
  MobileApplicationDetail: 'Mobile Application Details',
  ModerationRule: 'Moderation Rules',
  MutingPermissionSet: 'Muting Permission Sets',
  MyDomainDiscoverableLogin: 'MyDomain Discoverable Login',
  NamedCredential: 'Named Credentials',
  Network: 'Networks',
  NetworkBranding: 'Network Branding',
  NotificationTypeConfig: 'Notification Type Configs',
  OauthCustomScope: 'OAuth Custom Scopes',
  Orchestration: 'Orchestrations',
  OrchestrationContext: 'Orchestration Contexts',
  OutboundNetworkConnection: 'Outbound Network Connections',
  PathAssistant: 'Path Assistants',
  PaymentGatewayProvider: 'Payment Gateway Providers',
  PermissionSet: 'Permission Sets',
  PermissionSetGroup: 'Permission Set Groups',
  PlatformCachePartition: 'Platform Cache Partitions',
  PlatformEventChannel: 'Platform Event Channels',
  PlatformEventChannelMember: 'Platform Event Channel Members',
  Portal: 'Portals',
  PostTemplate: 'Post Templates',
  PresenceDeclineReason: 'Presence Decline Reasons',
  PresenceUserConfig: 'Presence User Configs',
  Profile: 'Profiles',
  ProfilePasswordPolicy: 'Profile Password Policies',
  ProfileSessionSetting: 'Profile Session Settings',
  Prompt: 'Prompts',
  Queue: 'Queues',
  QueueRoutingConfig: 'Queue Routing Configs',
  QuickAction: 'Quick Actions',
  RecommendationStrategy: 'Recommendation Strategies',
  RecordActionDeployment: 'Record Action Deployments',
  RecordType: 'Record Types',
  RedirectWhitelistUrl: 'Redirect Whitelist Url',
  RemoteSiteSetting: 'Remote Site Settings',
  Report: 'Reports',
  ReportFolder: 'Report Folders',
  ReportType: 'Report Types',
  Role: 'Roles',
  SamlSsoConfig: 'Saml Sso Configs',
  Scontrol: 'S-controls',
  ServiceChannel: 'Service Channels',
  ServicePresenceStatus: 'Service Presence Status',
  Settings: 'Settings',
  SharingCriteriaRule: 'Sharing Criteria Rules',
  SharingGuestRule: 'Sharing Guest Rule',
  SharingOwnerRule: 'Sharing Owner Rules',
  SharingReason: 'Sharing Reasons',
  SharingRules: 'Sharing Rules',
  SharingSet: 'Sharing Sets',
  SharingTerritoryRule: 'Sharing Territory Rules',
  SiteDotCom: 'Sites',
  Skill: 'Skills',
  StandardValueSet: 'Standard Value Sets',
  StandardValueSetTranslation: 'Standard Value Set Translations',
  StaticResource: 'Static Resources',
  SynonymDictionary: 'Synonym Dictionaries',
  Territory: 'Territories',
  Territory2: 'Territory2',
  Territory2Model: 'Territory2 Models',
  Territory2Rule: 'Territory2 Rules',
  Territory2Type: 'Territory2 Types',
  TopicsForObjects: 'Topics For Objects',
  TransactionSecurityPolicy: 'Transaction Security Policies',
  Translations: 'Translations',
  UiPlugin: 'Ui Plugins',
  UserCriteria: 'User Criteria',
  UserProvisioningConfig: 'User Provisioning Configs',
  ValidationRule: 'Validation Rules',
  VisualizationPlugin: 'Visualization Plugins',
  WaveApplication: 'Wave Applications',
  WaveDashboard: 'Wave Dashboards',
  WaveDataflow: 'Wave Dataflows',
  WaveDataset: 'Wave Datasets',
  WaveLens: 'Wave Lenses',
  WaveRecipe: 'Wave Recipes',
  WaveTemplateBundle: 'Wave Template Bundles',
  WaveXmd: 'Wave Xmd',
  WebLink: 'Web Links',
  Workflow: 'Workflows',
  WorkflowAlert: 'Workflow Alert',
  WorkflowFieldUpdate: 'Workflow Field Update',
  WorkflowKnowledgePublish: 'Workflow Knowledge Publish',
  WorkflowOutboundMessage: 'Workflow Outbound Message',
  WorkflowRule: 'Workflow Rule',
  WorkflowSend: 'Workflow Send',
  WorkflowTask: 'Workflow Task',
  XOrgHub: 'X Org Hubs',
};

export function getMetadataLabelFromFullName(fullName: string): string {
  return METADATA_LABEL_MAP[fullName] || fullName;
}
