export const data = [
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBn9AAF',
    },
    Id: '0036g00000EbBn9AAF',
    Name: 'Rose Gonzalez',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0HAAT',
      },
      BillingAddress: {
        city: 'Austin',
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'TX',
        street: '312 Constitution Place\nAustin, TX 78767\nUSA',
      },
      Description: '0016g00000ETu0HAAT',
      Id: '0016g00000ETu0HAAT',
      Name: 'Edge Communications',
    },
    AccountId: '0016g00000ETu0HAAT',
    Email: 'rose@edge.com',
    MailingAddress: {
      city: null,
      country: null,
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: null,
      state: null,
      street: '313 Constitution Place\nAustin, TX 78767\nUSA',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt973AAB',
        },
        Id: '5006g00000Bt973AAB',
        AccountId: '0016g00000ETu0HAAT',
        AssetId: null,
        Origin: 'Phone',
        CaseNumber: '00001000',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnAAAV',
    },
    Id: '0036g00000EbBnAAAV',
    Name: 'Sean Forbes',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0HAAT',
      },
      BillingAddress: {
        city: 'Austin',
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'TX',
        street: '312 Constitution Place\nAustin, TX 78767\nUSA',
      },
      Description: '0016g00000ETu0HAAT',
      Id: '0016g00000ETu0HAAT',
      Name: 'Edge Communications',
    },
    AccountId: '0016g00000ETu0HAAT',
    Email: 'sean@edge.com',
    MailingAddress: {
      city: 'Austin',
      country: 'USA',
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: '78767',
      state: 'TX',
      street: '312 Constitution Place',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97LAAR',
        },
        Id: '5006g00000Bt97LAAR',
        AccountId: '0016g00000ETu0HAAT',
        AssetId: null,
        Origin: 'Phone',
        CaseNumber: '00001018',
      },
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97KAAR',
        },
        Id: '5006g00000Bt97KAAR',
        AccountId: '0016g00000ETu0HAAT',
        AssetId: null,
        Origin: 'Web',
        CaseNumber: '00001017',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnBAAV',
    },
    Id: '0036g00000EbBnBAAV',
    Name: 'Jack Rogers',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0IAAT',
      },
      BillingAddress: {
        city: 'Burlington',
        country: 'USA',
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: '27215',
        state: 'NC',
        street: '525 S. Lexington Ave',
      },
      Description: '0016g00000ETu0IAAT',
      Id: '0016g00000ETu0IAAT',
      Name: 'Burlington Textiles Corp of America',
    },
    AccountId: '0016g00000ETu0IAAT',
    Email: 'jrogers@burlington.com',
    MailingAddress: {
      city: 'Burlington',
      country: 'USA',
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: '27215',
      state: 'NC',
      street: '525 S. Lexington Ave',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97NAAR',
        },
        Id: '5006g00000Bt97NAAR',
        AccountId: '0016g00000ETu0IAAT',
        AssetId: null,
        Origin: 'Phone',
        CaseNumber: '00001020',
      },
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97MAAR',
        },
        Id: '5006g00000Bt97MAAR',
        AccountId: '0016g00000ETu0IAAT',
        AssetId: null,
        Origin: 'Web',
        CaseNumber: '00001019',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnRAAV',
    },
    Id: '0036g00000EbBnRAAV',
    Name: 'Siddartha Nedaerk',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0SAAT',
      },
      BillingAddress: {
        city: 'San Francisco',
        country: 'US',
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: '94087',
        state: 'CA',
        street: 'The Landmark @ One Market',
      },
      Description: '0016g00000ETu0SAAT',
      Id: '0016g00000ETu0SAAT',
      Name: 'sForce',
    },
    AccountId: '0016g00000ETu0SAAT',
    Email: null,
    MailingAddress: {
      city: 'San Francisco',
      country: 'US',
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: '94087',
      state: 'CA',
      street: 'The Landmark @ One Market',
    },
    OtherAddress: null,
    Cases: null,
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnSAAV',
    },
    Id: '0036g00000EbBnSAAV',
    Name: 'Jake Llorrac',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0SAAT',
      },
      BillingAddress: {
        city: 'San Francisco',
        country: 'US',
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: '94087',
        state: 'CA',
        street: 'The Landmark @ One Market',
      },
      Description: '0016g00000ETu0SAAT',
      Id: '0016g00000ETu0SAAT',
      Name: 'sForce',
    },
    AccountId: '0016g00000ETu0SAAT',
    Email: null,
    MailingAddress: null,
    OtherAddress: null,
    Cases: null,
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnQAAV',
    },
    Id: '0036g00000EbBnQAAV',
    Name: 'Avi Green',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0MAAT',
      },
      BillingAddress: {
        city: 'New York',
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'NY',
        street: '1301 Avenue of the Americas \nNew York, NY 10019\nUSA',
      },
      Description: '0016g00000ETu0MAAT',
      Id: '0016g00000ETu0MAAT',
      Name: 'United Oil & Gas Corp.',
    },
    AccountId: '0016g00000ETu0MAAT',
    Email: 'agreen@uog.com',
    MailingAddress: {
      city: null,
      country: null,
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: null,
      state: null,
      street: '1302 Avenue of the Americas \nNew York, NY 10019\nUSA',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt974AAB',
        },
        Id: '5006g00000Bt974AAB',
        AccountId: '0016g00000ETu0MAAT',
        AssetId: null,
        Origin: 'Phone',
        CaseNumber: '00001001',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnEAAV',
    },
    Id: '0036g00000EbBnEAAV',
    Name: 'Tim Barr',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0LAAT',
      },
      BillingAddress: {
        city: 'Chicago',
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'IL',
        street: '2334 N. Michigan Avenue, Suite 1500\nChicago, IL 60601, USA',
      },
      Description: '0016g00000ETu0LAAT',
      Id: '0016g00000ETu0LAAT',
      Name: 'Grand Hotels & Resorts Ltd',
    },
    AccountId: '0016g00000ETu0LAAT',
    Email: 'barr_tim@grandhotels.com',
    MailingAddress: {
      city: null,
      country: null,
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: null,
      state: null,
      street: '2335 N. Michigan Avenue, Suite 1500\nChicago, IL 60601, USA',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97BAAR',
        },
        Id: '5006g00000Bt97BAAR',
        AccountId: '0016g00000ETu0LAAT',
        AssetId: null,
        Origin: 'Web',
        CaseNumber: '00001008',
      },
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97AAAR',
        },
        Id: '5006g00000Bt97AAAR',
        AccountId: '0016g00000ETu0LAAT',
        AssetId: null,
        Origin: 'Phone',
        CaseNumber: '00001007',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnFAAV',
    },
    Id: '0036g00000EbBnFAAV',
    Name: 'John Bond',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0LAAT',
      },
      BillingAddress: {
        city: 'Chicago',
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'IL',
        street: '2334 N. Michigan Avenue, Suite 1500\nChicago, IL 60601, USA',
      },
      Description: '0016g00000ETu0LAAT',
      Id: '0016g00000ETu0LAAT',
      Name: 'Grand Hotels & Resorts Ltd',
    },
    AccountId: '0016g00000ETu0LAAT',
    Email: 'bond_john@grandhotels.com',
    MailingAddress: {
      city: null,
      country: null,
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: null,
      state: null,
      street: '2334 N. Michigan Avenue, Suite 1500\nChicago, IL 60601, USA',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97HAAR',
        },
        Id: '5006g00000Bt97HAAR',
        AccountId: '0016g00000ETu0LAAT',
        AssetId: null,
        Origin: 'Phone',
        CaseNumber: '00001014',
      },
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97GAAR',
        },
        Id: '5006g00000Bt97GAAR',
        AccountId: '0016g00000ETu0LAAT',
        AssetId: null,
        Origin: 'Web',
        CaseNumber: '00001013',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnGAAV',
    },
    Id: '0036g00000EbBnGAAV',
    Name: 'Stella Pavlova',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0MAAT',
      },
      BillingAddress: {
        city: 'New York',
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'NY',
        street: '1301 Avenue of the Americas \nNew York, NY 10019\nUSA',
      },
      Description: '0016g00000ETu0MAAT',
      Id: '0016g00000ETu0MAAT',
      Name: 'United Oil & Gas Corp.',
    },
    AccountId: '0016g00000ETu0MAAT',
    Email: 'spavlova@uog.com',
    MailingAddress: {
      city: null,
      country: null,
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: null,
      state: null,
      street: '1303 Avenue of the Americas \nNew York, NY 10019\nUSA',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97PAAR',
        },
        Id: '5006g00000Bt97PAAR',
        AccountId: '0016g00000ETu0MAAT',
        AssetId: null,
        Origin: 'Web',
        CaseNumber: '00001022',
      },
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97QAAR',
        },
        Id: '5006g00000Bt97QAAR',
        AccountId: '0016g00000ETu0MAAT',
        AssetId: null,
        Origin: 'Phone',
        CaseNumber: '00001023',
      },
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97OAAR',
        },
        Id: '5006g00000Bt97OAAR',
        AccountId: '0016g00000ETu0MAAT',
        AssetId: null,
        Origin: 'Phone',
        CaseNumber: '00001021',
      },
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt975AAB',
        },
        Id: '5006g00000Bt975AAB',
        AccountId: '0016g00000ETu0MAAT',
        AssetId: null,
        Origin: 'Web',
        CaseNumber: '00001002',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnHAAV',
    },
    Id: '0036g00000EbBnHAAV',
    Name: 'Lauren Boyle',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0MAAT',
      },
      BillingAddress: {
        city: 'New York',
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'NY',
        street: '1301 Avenue of the Americas \nNew York, NY 10019\nUSA',
      },
      Description: '0016g00000ETu0MAAT',
      Id: '0016g00000ETu0MAAT',
      Name: 'United Oil & Gas Corp.',
    },
    AccountId: '0016g00000ETu0MAAT',
    Email: 'lboyle@uog.com',
    MailingAddress: {
      city: null,
      country: null,
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: null,
      state: null,
      street: '1304 Avenue of the Americas \nNew York, NY 10019\nUSA',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97SAAR',
        },
        Id: '5006g00000Bt97SAAR',
        AccountId: '0016g00000ETu0MAAT',
        AssetId: null,
        Origin: 'Phone',
        CaseNumber: '00001025',
      },
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97RAAR',
        },
        Id: '5006g00000Bt97RAAR',
        AccountId: '0016g00000ETu0MAAT',
        AssetId: null,
        Origin: 'Web',
        CaseNumber: '00001024',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnIAAV',
    },
    Id: '0036g00000EbBnIAAV',
    Name: 'Babara Levy',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0NAAT',
      },
      BillingAddress: {
        city: 'Portland',
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'OR',
        street: '620 SW 5th Avenue Suite 400\nPortland, Oregon 97204\nUnited States',
      },
      Description: '0016g00000ETu0NAAT',
      Id: '0016g00000ETu0NAAT',
      Name: 'Express Logistics and Transport',
    },
    AccountId: '0016g00000ETu0NAAT',
    Email: 'b.levy@expressl&t.net',
    MailingAddress: {
      city: null,
      country: null,
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: null,
      state: null,
      street: '620 SW 5th Avenue Suite 400\nPortland, Oregon 97204\nUnited States',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt977AAB',
        },
        Id: '5006g00000Bt977AAB',
        AccountId: '0016g00000ETu0NAAT',
        AssetId: null,
        Origin: 'Phone',
        CaseNumber: '00001004',
      },
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt976AAB',
        },
        Id: '5006g00000Bt976AAB',
        AccountId: '0016g00000ETu0NAAT',
        AssetId: null,
        Origin: 'Web',
        CaseNumber: '00001003',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnJAAV',
    },
    Id: '0036g00000EbBnJAAV',
    Name: 'Josh Davis',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0NAAT',
      },
      BillingAddress: {
        city: 'Portland',
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'OR',
        street: '620 SW 5th Avenue Suite 400\nPortland, Oregon 97204\nUnited States',
      },
      Description: '0016g00000ETu0NAAT',
      Id: '0016g00000ETu0NAAT',
      Name: 'Express Logistics and Transport',
    },
    AccountId: '0016g00000ETu0NAAT',
    Email: 'j.davis@expressl&t.net',
    MailingAddress: {
      city: null,
      country: null,
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: null,
      state: null,
      street: '621 SW 5th Avenue Suite 400\nPortland, Oregon 97204\nUnited States',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt978AAB',
        },
        Id: '5006g00000Bt978AAB',
        AccountId: '0016g00000ETu0NAAT',
        AssetId: null,
        Origin: 'Phone',
        CaseNumber: '00001005',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnKAAV',
    },
    Id: '0036g00000EbBnKAAV',
    Name: 'Jane Grey',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0OAAT',
      },
      BillingAddress: {
        city: 'Tucson',
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'AZ',
        street: '888 N Euclid \nHallis Center, Room 501\nTucson, AZ 85721\nUnited States',
      },
      Description: '0016g00000ETu0OAAT',
      Id: '0016g00000ETu0OAAT',
      Name: 'University of Arizona',
    },
    AccountId: '0016g00000ETu0OAAT',
    Email: 'jane_gray@uoa.edu',
    MailingAddress: {
      city: null,
      country: null,
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: null,
      state: null,
      street: '888 N Euclid \nHallis Center, Room 501\nTucson, AZ 85721\nUnited States',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97FAAR',
        },
        Id: '5006g00000Bt97FAAR',
        AccountId: '0016g00000ETu0OAAT',
        AssetId: null,
        Origin: 'Web',
        CaseNumber: '00001012',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnLAAV',
    },
    Id: '0036g00000EbBnLAAV',
    Name: 'Arthur Song',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0MAAT',
      },
      BillingAddress: {
        city: 'New York',
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'NY',
        street: '1301 Avenue of the Americas \nNew York, NY 10019\nUSA',
      },
      Description: '0016g00000ETu0MAAT',
      Id: '0016g00000ETu0MAAT',
      Name: 'United Oil & Gas Corp.',
    },
    AccountId: '0016g00000ETu0MAAT',
    Email: 'asong@uog.com',
    MailingAddress: {
      city: null,
      country: null,
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: null,
      state: null,
      street: '1301 Avenue of the Americas \nNew York, NY 10019\nUSA',
    },
    OtherAddress: null,
    Cases: null,
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnMAAV',
    },
    Id: '0036g00000EbBnMAAV',
    Name: 'Ashley James',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0PAAT',
      },
      BillingAddress: {
        city: null,
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'UK',
        street: 'Kings Park, 17th Avenue, Team Valley Trading Estate,\nGateshead, Tyne and Wear NE26 3HS\nUnited Kingdom',
      },
      Description: '0016g00000ETu0PAAT',
      Id: '0016g00000ETu0PAAT',
      Name: 'United Oil & Gas, UK',
    },
    AccountId: '0016g00000ETu0PAAT',
    Email: 'ajames@uog.com',
    MailingAddress: {
      city: null,
      country: null,
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: null,
      state: null,
      street: 'Kings Park, 17th Avenue, Team Valley Trading Estate,\nGateshead, Tyne and Wear NE26 3HS\nUnited Kingdom',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97CAAR',
        },
        Id: '5006g00000Bt97CAAR',
        AccountId: '0016g00000ETu0PAAT',
        AssetId: null,
        Origin: 'Phone',
        CaseNumber: '00001009',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnNAAV',
    },
    Id: '0036g00000EbBnNAAV',
    Name: 'Tom Ripley',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0QAAT',
      },
      BillingAddress: {
        city: 'Singapore',
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'Singapore',
        street: '9 Tagore Lane\nSingapore, Singapore 787472\nSingapore',
      },
      Description: '0016g00000ETu0QAAT',
      Id: '0016g00000ETu0QAAT',
      Name: 'United Oil & Gas, Singapore',
    },
    AccountId: '0016g00000ETu0QAAT',
    Email: 'tripley@uog.com',
    MailingAddress: {
      city: null,
      country: null,
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: null,
      state: null,
      street: '9 Tagore Lane\nSingapore, Singapore 787472\nSingapore',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97DAAR',
        },
        Id: '5006g00000Bt97DAAR',
        AccountId: '0016g00000ETu0QAAT',
        AssetId: null,
        Origin: 'Web',
        CaseNumber: '00001010',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnOAAV',
    },
    Id: '0036g00000EbBnOAAV',
    Name: "Liz D'Cruz",
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0QAAT',
      },
      BillingAddress: {
        city: 'Singapore',
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'Singapore',
        street: '9 Tagore Lane\nSingapore, Singapore 787472\nSingapore',
      },
      Description: '0016g00000ETu0QAAT',
      Id: '0016g00000ETu0QAAT',
      Name: 'United Oil & Gas, Singapore',
    },
    AccountId: '0016g00000ETu0QAAT',
    Email: 'ldcruz@uog.com',
    MailingAddress: {
      city: null,
      country: null,
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: null,
      state: null,
      street: '10 Tagore Lane\nSingapore, Singapore 787472\nSingapore',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97IAAR',
        },
        Id: '5006g00000Bt97IAAR',
        AccountId: '0016g00000ETu0QAAT',
        AssetId: null,
        Origin: 'Web',
        CaseNumber: '00001015',
      },
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97EAAR',
        },
        Id: '5006g00000Bt97EAAR',
        AccountId: '0016g00000ETu0QAAT',
        AssetId: null,
        Origin: 'Web',
        CaseNumber: '00001011',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000EbBnPAAV',
    },
    Id: '0036g00000EbBnPAAV',
    Name: 'Edna Frank',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000ETu0RAAT',
      },
      BillingAddress: {
        city: 'Mountain View',
        country: null,
        geocodeAccuracy: null,
        latitude: null,
        longitude: null,
        postalCode: null,
        state: 'CA',
        street: '345 Shoreline Park\nMountain View, CA 94043\nUSA',
      },
      Description: '0016g00000ETu0RAAT',
      Id: '0016g00000ETu0RAAT',
      Name: 'GenePoint',
    },
    AccountId: '0016g00000ETu0RAAT',
    Email: 'efrank@genepoint.com',
    MailingAddress: {
      city: null,
      country: null,
      geocodeAccuracy: null,
      latitude: null,
      longitude: null,
      postalCode: null,
      state: null,
      street: '345 Shoreline Park\nMountain View, CA 94043\nUSA',
    },
    OtherAddress: null,
    Cases: [
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt97JAAR',
        },
        Id: '5006g00000Bt97JAAR',
        AccountId: '0016g00000ETu0RAAT',
        AssetId: null,
        Origin: 'Web',
        CaseNumber: '00001016',
      },
      {
        attributes: {
          type: 'Case',
          url: '/services/data/v49.0/sobjects/Case/5006g00000Bt979AAB',
        },
        Id: '5006g00000Bt979AAB',
        AccountId: '0016g00000ETu0RAAT',
        AssetId: null,
        Origin: 'Phone',
        CaseNumber: '00001006',
      },
    ],
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000My0evAAB',
    },
    Id: '0036g00000My0evAAB',
    Name: 'Janet Jackson',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000MGMYrAAP',
      },
      BillingAddress: null,
      Description: '0016g00000MGMYrAAP',
      Id: '0016g00000MGMYrAAP',
      Name: 'my account 1',
    },
    AccountId: '0016g00000MGMYrAAP',
    Email: null,
    MailingAddress: null,
    OtherAddress: null,
    Cases: null,
  },
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v49.0/sobjects/Contact/0036g00000My0ewAAB',
    },
    Id: '0036g00000My0ewAAB',
    Name: 'Jay Johnson',
    Account: {
      attributes: {
        type: 'Account',
        url: '/services/data/v49.0/sobjects/Account/0016g00000MGMYsAAP',
      },
      BillingAddress: null,
      Description: '0016g00000MGMYsAAP',
      Id: '0016g00000MGMYsAAP',
      Name: 'my account 4',
    },
    AccountId: '0016g00000MGMYsAAP',
    Email: null,
    MailingAddress: null,
    OtherAddress: null,
    Cases: null,
  },
];
