import { ReleaseNote, releaseNoteSchema } from './release-notes.types';

/**
 * Generated by `pnpm release-notes:generate` from the MDX frontmatter in apps/docs/release-notes/
 * and committed as apps/docs/static/release-notes.json. The docs site serves it with
 * `Access-Control-Allow-Origin: *` so the web app, desktop app, and browser extension can all
 * fetch it cross-origin.
 */
export const RELEASE_NOTES_URL = 'https://docs.getjetstream.app/release-notes.json';

/**
 * Fetch the published release notes from the docs site.
 * Release notes are a progressive enhancement, so this never throws — any network,
 * HTTP, or payload-shape failure resolves to an empty array. Individual entries that
 * fail schema validation are skipped rather than rejecting the whole payload.
 */
export async function fetchReleaseNotes(url: string = RELEASE_NOTES_URL): Promise<ReleaseNote[]> {
  try {
    // The endpoint allows any origin without credentials; omit them so the wildcard CORS policy applies.
    const response = await fetch(url, { credentials: 'omit' });
    if (!response.ok) {
      return [];
    }
    const payload = await response.json();
    if (!Array.isArray(payload)) {
      return [];
    }
    return payload.flatMap((item) => {
      const parsed = releaseNoteSchema.safeParse(item);
      return parsed.success ? [parsed.data] : [];
    });
  } catch {
    return [];
  }
}
