import * as dotenv from 'dotenv';
import { readFileSync } from 'fs-extra';
import { join } from 'path';
dotenv.config();

let VERSION;
try {
  VERSION = readFileSync(join(__dirname, '../../VERSION'), 'utf-8').trim();
  console.info(`APP VERSION ${VERSION}`);
} catch {
  // could not read environment version
}

export const ENV = {
  // SYSTEM
  NODE_ENV: process.env.NODE_ENV,
  ENVIRONMENT: process.env.ENVIRONMENT || 'production',
  GIT_VERSION: VERSION,
  ROLLBAR_SERVER_TOKEN: process.env.ROLLBAR_SERVER_TOKEN,
  JETSTREAM_POSTGRES_DBURI: process.env.JETSTREAM_POSTGRES_DBURI,
  PRISMA_DEBUG: process.env.PRISMA_DEBUG && process.env.PRISMA_DEBUG.toLocaleLowerCase().startsWith('t'),

  // MAILGUN
  MAILGUN_API_KEY: process.env.MAILGUN_API_KEY,
  MAILGUN_PUBLIC_KEY: process.env.MAILGUN_PUBLIC_KEY,
  MAILGUN_WEBHOOK_KEY: process.env.MAILGUN_WEBHOOK_KEY,

  AMPLITUDE_API_KEY: process.env.AMPLITUDE_API_KEY,
  AMPLITUDE_SECRET_KEY: process.env.AMPLITUDE_SECRET_KEY,

  MAX_MIND_ACCOUNT_ID: process.env.MAX_MIND_ACCOUNT_ID,
  MAX_MIND_LICENSE_KEY: process.env.MAX_MIND_LICENSE_KEY,

  GEO_IP_API_HOSTNAME: process.env.GEO_IP_API_HOSTNAME,
  GEO_IP_API_USERNAME: process.env.GEO_IP_API_USERNAME,
  GEO_IP_API_PASSWORD: process.env.GEO_IP_API_PASSWORD,

  ADMIN_NOTIFICATION_EMAIL: process.env.ADMIN_NOTIFICATION_EMAIL,

  // CLOUDFLARE
  CLOUDFLARE_API_TOKEN: process.env.CLOUDFLARE_API_TOKEN,
  CLOUDFLARE_ZONE_IDS: process.env.CLOUDFLARE_ZONE_IDS, // comma-separated list of zone tags
  CLOUDFLARE_ALERT_RECIPIENT: process.env.CLOUDFLARE_ALERT_RECIPIENT, // falls back to ADMIN_NOTIFICATION_EMAIL if unset
  CLOUDFLARE_SPIKE_THRESHOLD_STDEV: process.env.CLOUDFLARE_SPIKE_THRESHOLD_STDEV,
  CLOUDFLARE_SPIKE_MIN_EVENTS: process.env.CLOUDFLARE_SPIKE_MIN_EVENTS,
  CLOUDFLARE_SPIKE_COOLDOWN_MINUTES: process.env.CLOUDFLARE_SPIKE_COOLDOWN_MINUTES,

  // CLOUDFLARE ANALYTICS ARCHIVE — separate Render Postgres database, public schema.
  CLOUDFLARE_ANALYTICS_DBURI: process.env.CLOUDFLARE_ANALYTICS_DBURI,
  CLOUDFLARE_ANALYTICS_MAX_BACKFILL_HOURS: process.env.CLOUDFLARE_ANALYTICS_MAX_BACKFILL_HOURS,
  CLOUDFLARE_ANALYTICS_ROW_LIMIT: process.env.CLOUDFLARE_ANALYTICS_ROW_LIMIT,
  CLOUDFLARE_ANALYTICS_RETENTION_DAYS: process.env.CLOUDFLARE_ANALYTICS_RETENTION_DAYS,
};
