export const environment = {
  name: 'Jetstream',
  production: true,
  rollbarClientAccessToken: import.meta.env.NX_PUBLIC_ROLLBAR_KEY,
  amplitudeToken: import.meta.env.NX_PUBLIC_AMPLITUDE_KEY,
  STRIPE_PUBLIC_KEY: import.meta.env.NX_PUBLIC_STRIPE_PUBLIC_KEY,
  STRIPE_BILLING_PORTAL_URL: import.meta.env.NX_PUBLIC_STRIPE_BILLING_PORTAL,
  STRIPE_ANNUAL_PRICE_ID: import.meta.env.NX_PUBLIC_STRIPE_ANNUAL_PRICE_ID,
  STRIPE_MONTHLY_PRICE_ID: import.meta.env.NX_PUBLIC_STRIPE_MONTHLY_PRICE_ID,
  MODE: import.meta.env.MODE,
  BASE_URL: import.meta.env.BASE_URL,
  PROD: import.meta.env.PROD,
  DEV: import.meta.env.DEV,
  SSR: import.meta.env.SSR,
};
