export const PASSWORD_RESET_DURATION_MINUTES = 30;
export const TOKEN_DURATION_MINUTES = 15;
export const EMAIL_VERIFICATION_TOKEN_DURATION_HOURS = 1;

export const DELETE_AUTH_ACTIVITY_DAYS = 365;
export const DELETE_EMAIL_ACTIVITY_DAYS = 180;
export const DELETE_TOKEN_DAYS = 3;
export const DELETE_MAILGUN_WEBHOOK_DAYS = 30;
export const DELETE_EXPIRED_DOMAIN_VERIFICATION_DAYS = 1;
