import type * as monaco from 'monaco-editor';
import { language } from './language-sfdc-formula';

type Monaco = typeof monaco;
const triggerChars = 'adefhijlmnsu';

export async function configureSfdcFormulaCompletions(monaco: Monaco) {
  monaco.languages.registerCompletionItemProvider('sfdc-formula', {
    triggerCharacters: ['.', ...triggerChars.split(''), ...triggerChars.toUpperCase().split('')],
    provideCompletionItems: (model, position, context, token) => {
      return {
        suggestions: getSuggestions(monaco, model, position),
      };
    },
  });
  // monaco.languages.registerHoverProvider('sfdc-formula', {
  //   provideHover: (model, position, token) => {},
  // });
}

function getSuggestions(monaco: Monaco, model: monaco.editor.ITextModel, position: monaco.Position): monaco.languages.CompletionItem[] {
  const textUntilPositionRaw = model.getValueInRange({
    startLineNumber: position.lineNumber,
    startColumn: 0,
    endLineNumber: position.lineNumber,
    endColumn: position.column,
  });

  const textUntilPosition = textUntilPositionRaw.trim();

  const mostRecentCharacter = model
    .getValueInRange({
      startLineNumber: position.lineNumber,
      startColumn: Math.max(position.column - 1, 0),
      endLineNumber: position.lineNumber,
      endColumn: position.column,
    })
    .trim();

  const getWordUntilPosition = model.getWordUntilPosition(position);

  const range = {
    startLineNumber: position.lineNumber,
    endLineNumber: position.lineNumber,
    startColumn: getWordUntilPosition.startColumn,
    endColumn: getWordUntilPosition.endColumn,
  };

  let completions: monaco.languages.CompletionItem[] = getSnippets(monaco, range);

  if (mostRecentCharacter === '.' || textUntilPosition.includes('.')) {
    // Dona't include formula snippets in this case
    completions = [];
  } else {
    completions = completions.concat(
      language.keywords.map((completion: string) => ({
        label: completion,
        kind: monaco.languages.CompletionItemKind.Class,
        insertText: completion,
        range: range,
      }))
    );
  }

  return completions;
}

/**
 * Built-in snippets that are always returned with completions
 * @param monaco
 * @param range
 * @returns
 */
function getSnippets(monaco: Monaco, range: monaco.IRange): monaco.languages.CompletionItem[] {
  const SNIPPETS: monaco.languages.CompletionItem[] = [
    {
      label: 'ABS(number)',
      documentation: 'Returns the absolute value of a number, a number without its sign',
      detail: 'MATH',
      filterText: 'ABS',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ABS(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ACOS(number)',
      documentation: 'Returns the arc cosine of the number in radians, if the given number is between -1 and 1.  Otherwise NULL.',
      detail: 'MATH',
      filterText: 'ACOS',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ACOS(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ADDMONTHS(date,num)',
      documentation:
        'Add the num months to the date, using the last date of the month if date is the last day of the month or adding num months has fewer days.',
      detail: 'DATE_TIME',
      filterText: 'ADDMONTHS',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ADDMONTHS(${1:date}, ${2:num})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'AGE(date)',
      documentation: 'Calculates the Age',
      detail: 'ADVANCED',
      filterText: 'AGE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'AGE(${1:date})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'AGEON(date,date)',
      documentation: 'Calculates the Age',
      detail: 'ADVANCED',
      filterText: 'AGEON',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'AGEON(${1:date}, ${2:date})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'AND(logical1,logical2,...)',
      documentation: 'Checks whether all arguments are true and returns TRUE if all arguments are true',
      detail: 'LOGICAL',
      filterText: 'AND',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'AND(${1:logical1}, ${2:logical2})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'CHR(text)',
      documentation: "Return the first character's code point from the given string as a number.",
      detail: 'TEXT',
      filterText: 'ASCII',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ASCII(${1:text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ASIN(number)',
      documentation: 'Returns the arc sine of the number in radians, if the given number is between -1 and 1.  Otherwise NULL.',
      detail: 'MATH',
      filterText: 'ASIN',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ASIN(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ATAN(number)',
      documentation: 'Returns the arc tangent of the number in radians.',
      detail: 'MATH',
      filterText: 'ATAN',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ATAN(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ATAN2(y, x)',
      documentation: 'Returns the arc tangent of the quotient of y and x in radians.',
      detail: 'MATH',
      filterText: 'ATAN2',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ATAN2(${1:ATAN2(y}, ${2:x})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'BEGINS(text, compare_text)',
      documentation: 'Checks if text begins with specified characters and returns TRUE if it does. Otherwise returns FALSE',
      detail: 'TEXT',
      filterText: 'BEGINS',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'BEGINS(${1:text}, ${2:compare_text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'BLANKVALUE(expression, substitute_expression)',
      documentation:
        'Checks whether expression is blank and returns substitute_expression if it is blank. If expression is not blank, returns the original expression value.',
      detail: 'LOGICAL',
      filterText: 'BLANKVALUE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'BLANKVALUE(${1:expression}, ${2:substitute_expression})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'BR()',
      documentation: 'Inserts an HTML break tag in string formulas',
      detail: 'TEXT',
      filterText: 'BR',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'BR(${1:})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'CASE(expression, value1, result1, value2, result2,...,else_result)',
      documentation:
        'Checks an expression against a series of values.  If the expression compares equal to any value, the corresponding result is returned. If it is not equal to any of the values, the else-result is returned',
      detail: 'LOGICAL',
      filterText: 'CASE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'CASE(\n\t${1:expression},\n\t${2:value1}, ${3:result1},\n\t${4:value2}, ${5:result2},\n\t${7:else_result}\n)',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'CASESAFEID(id)',
      documentation: 'Converts a 15-character ID into a case insensitive 18-character ID',
      detail: 'TEXT',
      filterText: 'CASESAFEID',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'CASESAFEID(${1:id})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'CEILING(number)',
      documentation: 'Rounds a number up to the nearest integer, away from zero if negative',
      detail: 'MATH',
      filterText: 'CEILING',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'CEILING(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'CHR(number)',
      documentation: "Return a string with the first character's code point as the given number.",
      detail: 'TEXT',
      filterText: 'CHR',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'CHR(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'CONTAINS(text, compare_text)',
      documentation: 'Checks if text contains specified characters, and returns TRUE if it does.  Otherwise, returns FALSE',
      detail: 'TEXT',
      filterText: 'CONTAINS',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'CONTAINS(${1:text}, ${2:compare_text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'COS(number)',
      documentation: 'Returns the cosine of the number, where the number given in radians',
      detail: 'MATH',
      filterText: 'COS',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'COS(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'CURRENCYRATE(IsoCode)',
      documentation:
        'Return the conversion rate to the corporate currency for the given CurrencyIsoCode, or 1.0 if the currency is invalid.',
      detail: 'ADVANCED',
      filterText: 'CURRENCYRATE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'CURRENCYRATE(${1:IsoCode})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'DATE(year,month,day)',
      documentation: 'Creates a date from a year, month and day',
      detail: 'DATE_TIME',
      filterText: 'DATE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'DATE(${1:year}, ${2:month}, ${3:day})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'DATETIMEVALUE(expression)',
      documentation: 'Returns a year, month, day and GMT time value',
      detail: 'DATE_TIME',
      filterText: 'DATETIMEVALUE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'DATETIMEVALUE(${1:expression})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'DATEVALUE(expression)',
      documentation: 'Creates a date from its datetime or text representation',
      detail: 'DATE_TIME',
      filterText: 'DATEVALUE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'DATEVALUE(${1:expression})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'DAY(date)',
      documentation: 'Returns the day of the month, a number between 1 and 31',
      detail: 'DATE_TIME',
      filterText: 'DAY',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'DAY(${1:date})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'DAYOFYEAR(date)',
      documentation: 'Return the day of the calendar year (from 1-366).',
      detail: 'DATE_TIME',
      filterText: 'DAYOFYEAR',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'DAYOFYEAR(${1:date})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'DISTANCE(location, location, unit)',
      documentation: 'Returns the distance between two locations using the provided unit.',
      detail: 'MATH',
      filterText: 'DISTANCE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'DISTANCE(${1:location}, ${2:location}, ${3:unit})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'EXP(number)',
      documentation: 'Returns e raised to the power of a given number',
      detail: 'MATH',
      filterText: 'EXP',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'EXP(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'FIND(search_text, text [, start_num])',
      documentation: 'Returns the position of the search_text string in text',
      detail: 'TEXT',
      filterText: 'FIND',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'FIND(${1:search_text}, text [, ${3:start_num]})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'FLOOR(number)',
      documentation: 'Rounds a number down, towards zero to the nearest integer',
      detail: 'MATH',
      filterText: 'FLOOR',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'FLOOR(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'FORMATDURATION(numSeconds[, includeDays] | dateTime/time, dateTime/time)',
      documentation: 'Format the number of seconds with optional days, or the difference between times or dateTimes as HH:MI:SS.',
      detail: 'DATE_TIME',
      filterText: 'FORMATDURATION',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'FORMATDURATION(numSeconds[, ${2:includeDays] | dateTime/time}, ${3:dateTime/time})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'FROMUNIXTIME(number)',
      documentation: 'Return the datetime that represents the given number as the seconds elapsed since 1 Jan 1970.',
      detail: 'DATE_TIME',
      filterText: 'FROMUNIXTIME',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'FROMUNIXTIME(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'GEOLOCATION(latitude, longitude)',
      documentation: 'Returns a location based on the provided latitude and longitude.',
      detail: 'MATH',
      filterText: 'GEOLOCATION',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'GEOLOCATION(${1:latitude}, ${2:longitude})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'GETRECORDIDS(object_type)',
      documentation:
        'Returns an array of record IDs for the selected records in a list such as list view or related list. Use $ObjectType to identify the type of records such as $ObjectType.Contact.',
      detail: 'ADVANCED',
      filterText: 'GETRECORDIDS',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'GETRECORDIDS(${1:object_type})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'GETSESSIONID()',
      documentation:
        'Returns the current session ID. This may be useful in hyperlinks to other applications that use salesforce.com credentials for authentication',
      detail: 'TEXT',
      filterText: 'GETSESSIONID',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'GETSESSIONID(${1:})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'HOUR(expression)',
      documentation: 'Returns hour of day',
      detail: 'DATE_TIME',
      filterText: 'HOUR',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'HOUR(${1:expression})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'HTMLENCODE(text)',
      documentation: 'Encodes text and merge field values for use in HTML',
      detail: 'TEXT',
      filterText: 'HTMLENCODE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'HTMLENCODE(${1:text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'HYPERLINK(url, friendly_name [, target])',
      documentation: 'Creates a hyperlink',
      detail: 'TEXT',
      filterText: 'HYPERLINK',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'HYPERLINK(${1:url}, friendly_name [, ${3:target]})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'IF(logical_test, value_if_true, value_if_false)',
      documentation: 'Checks whether a condition is true, and returns one value if TRUE and another value if FALSE.',
      detail: 'LOGICAL',
      filterText: 'IF',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'IF(\n\t${1:logical_test},\n\t${2:value_if_true},\n\t${3:value_if_false}\n)',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'IMAGE(image_url, alternate_text [, height, width])',
      documentation: 'Inserts an image',
      detail: 'TEXT',
      filterText: 'IMAGE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'IMAGE(${1:image_url}, alternate_text [, ${3:height}, ${4:width]})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'INCLUDE(source, [inputs])',
      documentation: 'Includes the selected source content with optional inputs expressed as query parameters',
      detail: 'ADVANCED',
      filterText: 'INCLUDE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'INCLUDE(${1:source}, [inputs])',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'INCLUDES(multiselect_picklist_field, text_literal)',
      documentation: 'Determines if any value selected in a multi-select picklist field equals a text literal you specify.',
      detail: 'TEXT',
      filterText: 'INCLUDES',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'INCLUDES(${1:multiselect_picklist_field}, ${2:text_literal})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'INITCAP(text)',
      documentation: 'Return the text as lowercase with first character of each word made uppercase.',
      detail: 'TEXT',
      filterText: 'INITCAP',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'INITCAP(${1:text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ISBLANK(expression)',
      documentation: 'Checks whether an expression is blank and returns TRUE or FALSE',
      detail: 'LOGICAL',
      filterText: 'ISBLANK',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ISBLANK(${1:expression})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ISCHANGED(field)',
      documentation:
        "Checks if the field's value is different from its prior value, and returns TRUE if the values differ.  Otherwise, returns FALSE",
      detail: 'ADVANCED',
      filterText: 'ISCHANGED',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ISCHANGED(${1:field})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ISCLONE()',
      documentation: 'Checks if the record is a clone of another record, and returns TRUE if it is a clone.  Otherwise, returns FALSE',
      detail: 'LOGICAL',
      filterText: 'ISCLONE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ISCLONE(${1:})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ISNEW()',
      documentation: 'Checks if the record is new, and returns TRUE if it is new.  Otherwise, returns FALSE',
      detail: 'LOGICAL',
      filterText: 'ISNEW',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ISNEW(${1:})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ISNULL(expression)',
      documentation: 'Checks whether an expression is null and returns TRUE or FALSE',
      detail: 'LOGICAL',
      filterText: 'ISNULL',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ISNULL(${1:expression})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ISNUMBER(Text)',
      documentation: 'Returns TRUE if the text value is a number. Otherwise, it returns FALSE.',
      detail: 'LOGICAL',
      filterText: 'ISNUMBER',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ISNUMBER(${1:Text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ISOWEEK(date)',
      documentation: 'Return the ISO 8601 week number for the given date (from 1-53) so that the first week starts on monday.',
      detail: 'DATE_TIME',
      filterText: 'ISOWEEK',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ISOWEEK(${1:date})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ISOYEAR(date)',
      documentation: 'Return the ISO 8601 week-numbering 4-digit year for the given date so that the first day is a monday.',
      detail: 'DATE_TIME',
      filterText: 'ISOYEAR',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ISOYEAR(${1:date})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ISPICKVAL(picklist_field, text_literal)',
      documentation: 'Checks whether the value of a picklist field is equal to a string literal',
      detail: 'TEXT',
      filterText: 'ISPICKVAL',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ISPICKVAL(${1:picklist_field}, ${2:text_literal})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'JSENCODE(text)',
      documentation: 'Encodes text and merge field values for use in JavaScript',
      detail: 'TEXT',
      filterText: 'JSENCODE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'JSENCODE(${1:text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'JSINHTMLENCODE(text)',
      documentation: 'Encodes text and merge field values for use in JavaScript within HTML tags',
      detail: 'TEXT',
      filterText: 'JSINHTMLENCODE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'JSINHTMLENCODE(${1:text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'JUNCTIONIDLIST(id,id,...)',
      documentation: 'Returns a JunctionIDList based on the provided IDs. You can enter IDs only.',
      detail: 'ADVANCED',
      filterText: 'JUNCTIONIDLIST',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'JUNCTIONIDLIST(${1:id}, ${2:id})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'LEFT(text, num_chars)',
      documentation: 'Returns the specified number of characters from the start of a text string',
      detail: 'TEXT',
      filterText: 'LEFT',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'LEFT(${1:text}, ${2:num_chars})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'LEN(text)',
      documentation: 'Returns the number of characters in a text string',
      detail: 'TEXT',
      filterText: 'LEN',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'LEN(${1:text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'LINKTO(label, target, id, [inputs], [no override])',
      documentation: 'Returns the HTML link element for the selected target with optional inputs expressed as query parameters',
      detail: 'ADVANCED',
      filterText: 'LINKTO',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'LINKTO(${1:label}, ${2:target}, ${3:id}, [inputs], [no override])',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'LN(number)',
      documentation: 'Returns the natural logarithm of a number',
      detail: 'MATH',
      filterText: 'LN',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'LN(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'LOG(number)',
      documentation: 'Returns the base 10 logarithm of n',
      detail: 'MATH',
      filterText: 'LOG',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'LOG(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'LOWER(text)',
      documentation: 'Converts all letters in the value to lowercase',
      detail: 'TEXT',
      filterText: 'LOWER',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'LOWER(${1:text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'LPAD(text, padded_length [, pad_string])',
      documentation: 'Pad the left side of the value with spaces or the optional pad string so that the length is padded_length',
      detail: 'TEXT',
      filterText: 'LPAD',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'LPAD(${1:text}, padded_length [, ${3:pad_string]})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'MAX(number,number,...)',
      documentation: 'Returns the greatest of all the arguments',
      detail: 'MATH',
      filterText: 'MAX',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'MAX(${1:number}, ${2:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'MCEILING(number)',
      documentation: 'Rounds a number up to the nearest integer, towards zero if negative',
      detail: 'MATH',
      filterText: 'MCEILING',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'MCEILING(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'MESSAGINGIMAGE(imageSrc, mimeType)',
      documentation: 'Returns an image reference to a URL image to be rendered in a conversation message.',
      detail: 'ADVANCED',
      filterText: 'MESSAGINGIMAGE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'MESSAGINGIMAGE(${1:imageSrc}, ${2:mimeType})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'MESSAGINGURLFOR(id)',
      documentation: 'Returns a public URL if available, for a record to be rendered in a conversation message template formula.',
      detail: 'ADVANCED',
      filterText: 'MESSAGINGURLFOR',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'MESSAGINGURLFOR(${1:id})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'MFLOOR(number)',
      documentation: 'Rounds a number down to the nearest integer, away from zero if negative',
      detail: 'MATH',
      filterText: 'MFLOOR',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'MFLOOR(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'MID(text, start_num, num_chars)',
      documentation: 'Returns character from the middle of a text string, given a starting position and length',
      detail: 'TEXT',
      filterText: 'MID',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'MID(${1:text}, ${2:start_num}, ${3:num_chars})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'MILLISECOND(expression)',
      documentation: 'Returns millisecond of day',
      detail: 'DATE_TIME',
      filterText: 'MILLISECOND',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'MILLISECOND(${1:expression})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'MIN(number,number,...)',
      documentation: 'Returns the least of all the arguments',
      detail: 'MATH',
      filterText: 'MIN',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'MIN(${1:number}, ${2:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'MINUTE(expression)',
      documentation: 'Returns minute of day',
      detail: 'DATE_TIME',
      filterText: 'MINUTE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'MINUTE(${1:expression})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'MOD(number,divisor)',
      documentation: 'Returns the remainder after a number is divided by a divisor',
      detail: 'MATH',
      filterText: 'MOD',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'MOD(${1:number}, ${2:divisor})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'MONTH(date)',
      documentation: 'Returns the month, a number between 1 (January) and 12 (December)',
      detail: 'DATE_TIME',
      filterText: 'MONTH',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'MONTH(${1:date})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'NOT(logical)',
      documentation: 'Changes FALSE to TRUE or TRUE to FALSE',
      detail: 'LOGICAL',
      filterText: 'NOT',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'NOT(${1:logical})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'NOW()',
      documentation: 'Returns a datetime representing the current moment',
      detail: 'DATE_TIME',
      filterText: 'NOW',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'NOW(${1:})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'NULLVALUE(expression, substitute_expression)',
      documentation:
        'Checks whether expression is null and returns substitute_expression if it is null. If expression is not null, returns the original expression value.',
      detail: 'LOGICAL',
      filterText: 'NULLVALUE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'NULLVALUE(${1:expression}, ${2:substitute_expression})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'OR(logical1,logical2,...)',
      documentation:
        'Checks whether any of the arguments are true and returns TRUE or FALSE.  Returns FALSE only if all arguments are false',
      detail: 'LOGICAL',
      filterText: 'OR',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'OR(${1:logical1}, ${2:logical2})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'PARENTGROUPVAL(summary_field, grouping_level)',
      documentation: 'Calculates the value of a summary field for a specified grouping level higher than the formula display level.',
      detail: 'REPORT_SUMMARIES',
      filterText: 'PARENTGROUPVAL',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'PARENTGROUPVAL(${1:summary_field}, ${2:grouping_level})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'PI()',
      documentation: 'Returns pi',
      detail: 'MATH',
      filterText: 'PI',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'PI(${1:})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'PICKLISTCOUNT(multiselect_picklist_field)',
      documentation: 'Returns the number of selected values in a multi-select picklist.',
      detail: 'TEXT',
      filterText: 'PICKLISTCOUNT',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'PICKLISTCOUNT(${1:multiselect_picklist_field})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'PREDICT(PredDefId, [recordId] | [field, value, ...])',
      documentation: 'Returns an Einstein Discovery prediction based on either a record ID or a list of fields and their values.',
      detail: 'ADVANCED',
      filterText: 'PREDICT',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'PREDICT(${1:PredDefId}, [recordId] | [field, ${3:value}, ${4:...]})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'PREVGROUPVAL(summary_field, grouping_level [, increment])',
      documentation:
        'Gets the value of a summary field from the previous grouping (1 increment back by default) at the specified grouping level. Returns null if no previous grouping.',
      detail: 'REPORT_SUMMARIES',
      filterText: 'PREVGROUPVAL',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'PREVGROUPVAL(${1:summary_field}, grouping_level [, ${3:increment]})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'PRIORVALUE(field)',
      documentation: 'Returns the previous value for the field',
      detail: 'LOGICAL',
      filterText: 'PRIORVALUE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'PRIORVALUE(${1:field})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'REGEX(Text, RegEx_Text)',
      documentation: 'Returns TRUE if Text matches the regular expression RegEx_Text. Otherwise, it returns FALSE.',
      detail: 'ADVANCED',
      filterText: 'REGEX',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'REGEX(${1:Text}, ${2:RegEx_Text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'REQUIRESCRIPT(url)',
      documentation: 'Creates html script element that references the external script identified by url',
      detail: 'ADVANCED',
      filterText: 'REQUIRESCRIPT',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'REQUIRESCRIPT(${1:url})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'RIGHT(text, num_chars)',
      documentation: 'Returns the specified number of characters from the end of a text string',
      detail: 'TEXT',
      filterText: 'RIGHT',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'RIGHT(${1:text}, ${2:num_chars})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'ROUND(number,num_digits)',
      documentation: 'Rounds a number to a specified number of digits',
      detail: 'MATH',
      filterText: 'ROUND',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'ROUND(${1:number}, ${2:num_digits})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'RPAD(text, padded_length [, pad_string])',
      documentation: 'Pad the right side of the value with spaces or the optional pad string so that the length is padded_length',
      detail: 'TEXT',
      filterText: 'RPAD',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'RPAD(${1:text}, padded_length [, ${3:pad_string]})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'SECOND(expression)',
      documentation: 'Returns second of day',
      detail: 'DATE_TIME',
      filterText: 'SECOND',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'SECOND(${1:expression})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'SIN(number)',
      documentation: 'Returns the sine of the number, where the number given in radians',
      detail: 'MATH',
      filterText: 'SIN',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'SIN(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'SQRT(number)',
      documentation: 'Returns the positive square root of a number',
      detail: 'MATH',
      filterText: 'SQRT',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'SQRT(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'SUBSTITUTE(text, old_text, new_text)',
      documentation:
        'Substitutes new_text for old_text in a text string. Use SUBSTITUTE when you want to replace specific text in a text string',
      detail: 'TEXT',
      filterText: 'SUBSTITUTE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'SUBSTITUTE(${1:text}, ${2:old_text}, ${3:new_text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'TAN(number)',
      documentation: 'Returns the tangent of the number, where the number given in radians',
      detail: 'MATH',
      filterText: 'TAN',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'TAN(${1:number})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'TEXT(value)',
      documentation: 'Converts a value to text using standard display format',
      detail: 'TEXT',
      filterText: 'TEXT',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'TEXT(${1:value})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'TIMENOW()',
      documentation: 'Returns a time representing the current moment',
      detail: 'DATE_TIME',
      filterText: 'TIMENOW',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'TIMENOW(${1:})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'TIMEVALUE(expression)',
      documentation: 'Returns a time',
      detail: 'DATE_TIME',
      filterText: 'TIMEVALUE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'TIMEVALUE(${1:expression})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'TODAY()',
      documentation: 'Returns the current date',
      detail: 'DATE_TIME',
      filterText: 'TODAY',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'TODAY(${1:})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'TRIM(text)',
      documentation: 'Removes all spaces from a text string except for single spaces between words',
      detail: 'TEXT',
      filterText: 'TRIM',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'TRIM(${1:text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'TRUNC(number,num_digits)',
      documentation: 'Truncates a number to a specified number of digits',
      detail: 'MATH',
      filterText: 'TRUNC',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'TRUNC(${1:number}, ${2:num_digits})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'UNIXTIMESTAMP(date/time)',
      documentation: 'Return the number of seconds since 1 Jan 1970 for the given date, or number of seconds in the day for a time.',
      detail: 'DATE_TIME',
      filterText: 'UNIXTIMESTAMP',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'UNIXTIMESTAMP(${1:date/time})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'UPPER(text)',
      documentation: 'Converts all letters in the value to uppercase',
      detail: 'TEXT',
      filterText: 'UPPER',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'UPPER(${1:text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'URLENCODE(text)',
      documentation: 'Encodes text and merge field values for use in URLs',
      detail: 'TEXT',
      filterText: 'URLENCODE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'URLENCODE(${1:text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'URLFOR(target, id, [inputs], [no override])',
      documentation: 'Returns the url for the selected target with optional inputs expressed as query parameters',
      detail: 'ADVANCED',
      filterText: 'URLFOR',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'URLFOR(${1:target}, ${2:id}, [inputs], [no override])',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'VALUE(text)',
      documentation: 'Converts a text string that represents a number to a number',
      detail: 'TEXT',
      filterText: 'VALUE',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'VALUE(${1:text})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'VLOOKUP(field_to_return, field_on_lookup_object, lookup_value)',
      documentation:
        'Searches an object for a record where the specified field matches the specified lookup_value. If a match is found, returns another specified field value.',
      detail: 'ADVANCED',
      filterText: 'VLOOKUP',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'VLOOKUP(${1:field_to_return}, ${2:field_on_lookup_object}, ${3:lookup_value})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'WEEKDAY(date)',
      documentation: 'Return the day of the week for the given date, using 1 for Sunday, 2 for Monday, through 7 for Saturday.',
      detail: 'DATE_TIME',
      filterText: 'WEEKDAY',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'WEEKDAY(${1:date})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
    {
      label: 'YEAR(date)',
      documentation: 'Returns the year of a date, a number between 1900 and 9999',
      detail: 'DATE_TIME',
      filterText: 'YEAR',
      kind: monaco.languages.CompletionItemKind.Function,
      insertText: 'YEAR(${1:date})',
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      range: range,
    },
  ];
  return SNIPPETS;
}
