import { FieldDefinitionType, FieldValue } from '@jetstream/ui-core';

export const CREATE_FIELDS_EXAMPLE_TEMPLATE: Record<FieldDefinitionType, FieldValue>[] = [
  {
    type: 'AutoNumber',
    label: 'Autonumber',
    fullName: 'Autonumber',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '',
    scale: '',
    required: '',
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: 'a-{0000}',
    startingNumber: '0',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: true,
  },
  {
    type: 'Checkbox',
    label: 'Checkbox Field',
    fullName: 'Checkbox_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: false,
    precision: '',
    scale: '',
    required: '',
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'Currency',
    label: 'Currency Field',
    fullName: 'Currency_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '16',
    scale: '2',
    required: true,
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'Date',
    label: 'Date Field',
    fullName: 'Date_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '',
    scale: '',
    required: false,
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'DateTime',
    label: 'Date Time Field',
    fullName: 'Date_Time_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '',
    scale: '',
    required: false,
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'Email',
    label: 'Email Field',
    fullName: 'Email_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '',
    scale: '',
    required: false,
    unique: false,
    externalId: false,
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'Formula',
    label: 'Formula Field',
    fullName: 'Formula_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '',
    scale: '',
    required: '',
    unique: '',
    externalId: '',
    formula: 'Name + " TADA!"',
    formulaTreatBlanksAs: 'BlankAsZero',
    secondaryType: 'Text',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'Lookup',
    label: 'Lookup Field',
    fullName: 'Lookup_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '',
    scale: '',
    required: false,
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: 'Account',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: 'ChildRelName',
    deleteConstraint: 'SetNull',
    populateExistingRows: '',
  },
  {
    type: 'MasterDetail',
    label: 'Master Detail Field',
    fullName: 'Master_Detail_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '',
    scale: '',
    required: '',
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: 'Contact',
    writeRequiresMasterRead: 'true',
    reparentableMasterDetail: false,
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: 'ChildRelName',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'Number',
    label: 'Number Field',
    fullName: 'Number_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '18',
    scale: '0',
    required: false,
    unique: false,
    externalId: true,
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'Percent',
    label: 'Percent Field',
    fullName: 'Percent_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '18',
    scale: '0',
    required: false,
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'Phone',
    label: 'Phone Field',
    fullName: 'Phone_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '',
    scale: '',
    required: false,
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'Picklist',
    label: 'Picklist Field',
    fullName: 'Picklist_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '',
    scale: '',
    required: false,
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: 'One\nTwo\nThree',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: true,
    restricted: true,
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'Picklist',
    label: 'Picklist Field (Global)',
    fullName: 'Picklist_Field_Global',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '',
    scale: '',
    required: false,
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: 'SBQQ__BillingFrequency',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: false,
    restricted: true,
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'Text',
    label: 'Text Field',
    fullName: 'Text_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '255',
    defaultValue: '',
    precision: '',
    scale: '',
    required: false,
    unique: false,
    externalId: true,
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'TextArea',
    label: 'Textarea Field',
    fullName: 'Textarea_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '',
    scale: '',
    required: false,
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'LongTextArea',
    label: 'Textarea (Long) Field',
    fullName: 'Textarea_Long_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '131072',
    defaultValue: '',
    precision: '',
    scale: '',
    required: '',
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '3',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'Html',
    label: 'Textarea (Rich) Field',
    fullName: 'Textarea_Rich_Field',
    inlineHelpText: 'Help Text',
    description: '',
    length: '131072',
    defaultValue: '',
    precision: '',
    scale: '',
    required: '',
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '10',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'Time',
    label: 'Time Field',
    fullName: 'Time_Field',
    inlineHelpText: 'Help Text',
    description: '',
    length: '',
    defaultValue: '',
    precision: '',
    scale: '',
    required: false,
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
  {
    type: 'Url',
    label: 'Url Field',
    fullName: 'Url_Field',
    inlineHelpText: 'Help Text',
    description: 'Description',
    length: '',
    defaultValue: '',
    precision: '',
    scale: '',
    required: false,
    unique: '',
    externalId: '',
    formula: '',
    formulaTreatBlanksAs: '',
    secondaryType: '',
    displayFormat: '',
    startingNumber: '',
    valueSet: '',
    globalValueSet: '',
    referenceTo: '',
    writeRequiresMasterRead: '',
    reparentableMasterDetail: '',
    firstAsDefault: '',
    restricted: '',
    visibleLines: '',
    relationshipName: '',
    deleteConstraint: '',
    populateExistingRows: '',
  },
];
