name: Docs CI

on:
  push:
    branches:
      - main
    paths:
      - "apps/docs/**"
      - ".github/workflows/docs.yml"
  pull_request:
    paths:
      - "apps/docs/**"
      - ".github/workflows/docs.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        working-directory: apps/docs
        run: yarn install --frozen-lockfile

      - name: Build docs
        working-directory: apps/docs
        run: yarn build